# -*- coding: utf-8 -*-
"""FEEDBACK_LOOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z170hug7p7UrrDJ9rcJll0dPhYGvhq79

🔁 Lab 2 — Prompt Feedback Loop with Automatic Iteration (Groq Edition)
Day 13 · Module 5 · FinSight AI Credit Risk Scenario

🎯 Learning Objectives
By the end of this lab you will be able to:

Instrument LLM calls with structured logging to a persistent SQLite store
Build an automated quality probe to detect failure modes at scale
Triage failure patterns using frequency analysis
Write a revised prompt based on failure evidence, not intuition
Demonstrate measurable improvement through a before/after evaluation
🏦 Backbone Scenario: FinSight AI — Production Feedback Loop
FinSight has deployed LLaMA 3.3 70B on Groq (from Lab 1). After 2 weeks in production, the team has collected 50 memo requests. Your job: find what's failing and fix it.

💡 All API calls in this lab use Groq only — a single GROQ_API_KEY is all you need.
"""

!pip install groq bert-score pandas matplotlib seaborn numpy scikit-learn tqdm -q
print('✅ Dependencies installed')


import os, sqlite3, json, time, re, hashlib, random, uuid
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm
from dataclasses import dataclass, asdict
from typing import Optional
from datetime import datetime, timedelta
from google.colab import userdata

# ── API Key ───────────────────────────────────────────────────────
try:
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
except:
    GROQ_API_KEY = 'gsk_YOUR_GROQ_KEY_HERE'

os.environ['GROQ_API_KEY'] = GROQ_API_KEY

from groq import Groq
groq_client = Groq(api_key=GROQ_API_KEY)

# ── Model to use for memo generation (from Lab 1 winner) ─────────
# Change this to experiment with different Groq models
PRODUCTION_MODEL = 'llama-3.3-70b-versatile'

# ── Groq cost helper ─────────────────────────────────────────────
GROQ_PRICING = {
    'llama-3.3-70b-versatile': {'input': 0.59, 'output': 0.79},
    'llama-3.1-8b-instant':    {'input': 0.05, 'output': 0.08},
    'mixtral-8x7b-32768':      {'input': 0.24, 'output': 0.24},
    'gemma2-9b-it':            {'input': 0.20, 'output': 0.20},
}

def compute_cost(model_id, input_tokens, output_tokens):
    p = GROQ_PRICING.get(model_id, {'input': 0.5, 'output': 0.5})
    return (input_tokens * p['input'] + output_tokens * p['output']) / 1_000_000

print('✅ Setup complete')
print(f'   Production model: {PRODUCTION_MODEL}')

"""Step 1 — Design the Logging Schema & SQLite Database"""

# ── Structured log entry dataclass ───────────────────────────────────
@dataclass
class LLMLogEntry:
    request_id:        str     # Unique ID for this call
    timestamp:         str     # ISO 8601
    prompt_version:    str     # e.g. 'v1.0', 'v1.1', 'v2.0'
    prompt_hash:       str     # MD5 of prompt template (for deduplication)
    model:             str     # Groq model ID
    task_type:         str     # 'credit_memo'
    borrower_id:       str     # Anonymised ID
    input_tokens:      int
    output_tokens:     int
    latency_ms:        float
    cost_usd:          float
    output_text:       str
    output_word_count: int
    # Quality signals (populated post-call)
    auto_score:           Optional[float] = None   # BERTScore or rubric score
    hallucination_flag:   Optional[bool]  = None
    hallucination_count:  Optional[int]   = None
    missing_sections:     Optional[str]   = None   # JSON list of absent sections
    user_correction:      Optional[bool]  = None   # Simulated analyst feedback
    failure_category:     Optional[str]   = None   # Populated during triage
    environment:          str = 'production'


def init_db(db_path: str = 'finsight_logs_groq.db') -> sqlite3.Connection:
    """Create SQLite database with logging schema."""
    conn = sqlite3.connect(db_path)
    conn.execute('''
        CREATE TABLE IF NOT EXISTS llm_logs (
            request_id          TEXT PRIMARY KEY,
            timestamp           TEXT,
            prompt_version      TEXT,
            prompt_hash         TEXT,
            model               TEXT,
            task_type           TEXT,
            borrower_id         TEXT,
            input_tokens        INTEGER,
            output_tokens       INTEGER,
            latency_ms          REAL,
            cost_usd            REAL,
            output_text         TEXT,
            output_word_count   INTEGER,
            auto_score          REAL,
            hallucination_flag  INTEGER,
            hallucination_count INTEGER,
            missing_sections    TEXT,
            user_correction     INTEGER,
            failure_category    TEXT,
            environment         TEXT
        )
    ''')
    conn.commit()
    return conn


def log_entry(conn: sqlite3.Connection, entry: LLMLogEntry) -> None:
    """Insert a log entry into the database."""
    d = asdict(entry)
    d['hallucination_flag'] = int(d['hallucination_flag']) if d['hallucination_flag'] is not None else None
    d['user_correction']    = int(d['user_correction'])    if d['user_correction']    is not None else None
    conn.execute(
        f"INSERT OR REPLACE INTO llm_logs VALUES ({','.join(['?']*len(d))})",
        list(d.values())
    )
    conn.commit()


conn = init_db()
print('✅ SQLite database initialised: finsight_logs_groq.db')
print('   Schema:', [col[0] for col in conn.execute('PRAGMA table_info(llm_logs)').fetchall()])

"""Step 2 — Define Prompt Variants"""

# ── Prompt variants to test ────────────────────────────────────────────
# v1.0: Minimal prompt (baseline — simulates what a rushed team ships)
PROMPT_V1_0 = {
    'version': 'v1.0',
    'system':  'You are a credit analyst. Generate a credit risk memo based on the borrower data.',
    'user_template': 'Borrower data:\n{data}\n\nWrite a credit memo.',
}

# v1.1: Structured output prompt
PROMPT_V1_1 = {
    'version': 'v1.1',
    'system': '''You are a credit analyst AI at FinSight AI.
Generate a credit risk memo (150-250 words) structured as:
1. BORROWER OVERVIEW
2. KEY FINANCIAL METRICS
3. RISK ASSESSMENT
4. RECOMMENDATION
Use only the data provided. Do not extrapolate or add information not given.''',
    'user_template': 'Generate a credit memo for:\n{data}',
}

# v2.0: Chain-of-thought + anti-hallucination guardrails
PROMPT_V2_0 = {
    'version': 'v2.0',
    'system': '''You are a senior credit analyst at FinSight AI, operating in a regulated lending environment.

PROCESS:
Step 1: List every numeric fact explicitly stated in the borrower data.
Step 2: Identify any internal inconsistencies or missing data.
Step 3: Write the credit memo using ONLY those stated facts.

MEMO FORMAT (150-250 words):
BORROWER OVERVIEW: [company name, industry, loan request]
KEY FINANCIAL METRICS: [cite exact figures from data; flag any gaps]
RISK ASSESSMENT: [strengths and risk factors based only on provided data]
RECOMMENDATION: [approve/decline/conditional with rationale]

COMPLIANCE RULES:
- Never state a number not explicitly given in the input
- If data is inconsistent, note it: "Note: figures appear inconsistent — [detail]"
- Use hedged language for projections: "based on provided data" not "will" or "certainly"
- If insufficient data exists for a section, write: "Insufficient data provided for [section]"''',
    'user_template': 'Generate a credit memo for the following borrower.\n\nBORROWER DATA:\n{data}',
}

ALL_PROMPTS = [PROMPT_V1_0, PROMPT_V1_1, PROMPT_V2_0]

def hash_prompt(system: str, template: str) -> str:
    return hashlib.md5((system + template).encode()).hexdigest()[:8]

for p in ALL_PROMPTS:
    h = hash_prompt(p['system'], p['user_template'])
    print(f"  {p['version']} → hash: {h}")
print('✅ Prompt variants defined')

"""### Step 3a — LangSmith Tracing Setup (for all simulations)

This section installs the necessary libraries and configures LangSmith environment variables so that all subsequent LLM calls are traced automatically.
"""

# ── LangSmith Setup ────────────────────────────────────────────────
!pip install langsmith langchain-groq -q

import os
from google.colab import userdata

os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_API_KEY']    = userdata.get('LANGCHAIN_API_KEY')
os.environ['LANGCHAIN_PROJECT']    = 'finsight-feedback-loop-groq'

print('✅ LangSmith setup complete (ensure LANGCHAIN_API_KEY is in Colab secrets)')

"""### Step 3b — Traced LLM Call Function

This function is a LangSmith-integrated version of the LLM caller, designed to replace the original untraced `call_model_with_prompt`.
"""

from langsmith import traceable
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

@traceable(name='traced_llm_call')
def traced_call_model_with_prompt(prompt_cfg: dict, borrower_data: str,
                                  model_id: str = PRODUCTION_MODEL) -> dict:
    """Call Groq with LangSmith tracing and return output + token + latency + cost data."""
    user_msg = prompt_cfg['user_template'].format(data=borrower_data)
    messages = [
        SystemMessage(content=prompt_cfg['system']),
        HumanMessage(content=user_msg)
    ]

    # Instantiate ChatGroq (relies on os.environ['GROQ_API_KEY'] set earlier)
    llm = ChatGroq(model=model_id, temperature=0.0)

    start = time.time()
    try:
        response = llm.invoke(messages)
        latency_ms = (time.time() - start) * 1000

        output = response.content

        # Calculate token counts using LangChain's methods for compatibility
        input_tokens = llm.get_num_tokens_from_messages(messages)
        output_tokens = llm.get_num_tokens(output)

        cost = compute_cost(model_id, input_tokens, output_tokens)

        return {
            'output': output,
            'input_tokens': input_tokens,
            'output_tokens': output_tokens,
            'latency_ms': round(latency_ms, 1),
            'cost': cost,
            'error': None,
        }
    except Exception as e:
        return {'output': '', 'input_tokens': 0, 'output_tokens': 0,
                'latency_ms': (time.time() - start) * 1000, 'cost': 0, 'error': str(e)}

print('✅ traced_call_model_with_prompt function defined')

"""Step 3 — Simulate 50 Production Requests with Full Logging"""

BORROWER_PROFILES = [
    'Northgate Logistics. Revenue 8.2M. EBITDA1.1M. Debt 2,5M. DSC R1.7%. Loarrequest1.5M.',
    'Sunrise Bakeries. Revenue 3.4M. Netprofit280K. No existing debt. Loan request $400K equipment.',
    'Harbor Bridge Industrial. Revenue 19.5M. EBITDA3.2M. Existing debt 6.8M. Collateral9.1M. Loan $2M.',
    'Tech. ARR 2.1M. Growth 1885K/mo. Runway 18mo. Loan request $300K.',
    'Westfield Blue Ridge Farms. Revenue 5.9M. Seasonal. DSCR1 40. Cropinsurance Loanreques 1900K operating line.',
    'Delta Medical Supplies. Revenue 11.2M. Grossmargin341.8M.',
    'Summit Construction. Revenue 28M. Grossmargin912M. DSCR 1.5x. Loan $3.5M.',
    'Coastal Realty Trust. Properties 8. NAV 14.2M. LTV581.5M.',
    'Ironwood Software. ARR 48M. NRR118600K.',
    'Pacific Fisheries. Revenue 7.1M. EBITDA900K. Fleet value 3.8M. DSCR1.3 Loanl.1M.',

    # Slightly tricky
    'NovaStar Retail. Revenue 15M(down12800K. High lease obligations 3.2M/yr. Loan 2 M.',
    'Vertex Energy. Revenue 9.2M. EBITDA1.4M. BUT Q3 one-time gain 600K no tezcluded. True EBITDA800K. Loan $1.51',
    'Cascade Healthcare. Revenue 6.8M. Receivables 2.1M (90-day overdue 35%). DSCR 1.2x. Loan $800K.',
    'Alpine Hotels. Revenue 12M. Seasonality: 602.21.',
    'TechVenture Alpha. Pre-revenue. VC backed 3M. Burn180K/mo. Patent pending. Loan $400K bridge.',
    'Heritage Textiles. Revenue 4.1M. Stable. Oumeragebano succes rionplan. DSCR1. 90. Loan 600K.',
    'Meridian Imports. Revenue 22M. Singdecustomer653 M.',
    'Quantum Logistics. Revenue 17M. Growing Tightworkingoapital. Currentratio0.9. Loan2.5M.',
    'Bluestone Mining. Revenue 8.7M. Commoditricesensitive. Insuranceinplace. DSC R1.60. Loan1.4M.',
    'RapidGrow Foods. Revenue 6.2M. EBITDAmargins tated 281M.',

    #Adversarial: missing data
    'Unnamed LLC. Some revenue. Requesting $500K. Business started recently.',
    'Apex Corp. Revenue not disclosed. Assets 2M.Loan800K.',
    'XYZ Holdings. Revenue 5M. Nootherfinancial dataprovided. Need750K urgently.',
    'Global Partners. Profitable. Good DSCR. Loan $1.2M.',
    'MegaBuild Inc. Revenue 100M. EBITDA50M. (Implausibly high margin for construction at 50%). Loan $5',

    #Adversarial: inconsistent numbers
    'BrightPath Energy. Revenue 12M. Netincome3.6M (30% margin). But tax paid 50Xonly. DSC R1.8m. Loan2 M.',
    'Frontier Exports. Revenue 18M. EBITDA2.7M. Debt service 2.1M. Stated DSCR1.8% (actual: 1.32). Loan3 M.',
    'ClearView Media. ARR 1.8M.MRR200K. Note: 200K-12-2.4M not 1.8M. Loan400K.',
    'Skyline Builders. Properties appraised 20M. Debt15M. Stated LTV 60% (actual 75%). Loan $2.5M.',
    'Neptune Pharma. Revenue 9.1M. Grossmargin 726.8M. Implied operating margin 24 but claims 15%. Loan $1.5'
] * 2 # Repeat to reach 50 entries

BORROWER_PROFILES = BORROWER_PROFILES[:50]

# ── Run simulation: v1.0 prompt on 50 requests ────────────────────
print('Simulating 50 production requests with prompt v1.0...')
print('(Set SIMULATE_N = 50 for the full run; 10 shown for speed)')

SIMULATE_N = 10   # ← Change to 50 for full simulation
PROMPT_CFG = PROMPT_V1_0  # Baseline prompt

sim_start = datetime(2025, 6, 1, 9, 0, 0)

for i, borrower_data in enumerate(tqdm(BORROWER_PROFILES[:SIMULATE_N], desc='Simulating')):
    result = traced_call_model_with_prompt(PROMPT_CFG, borrower_data) # <--- Changed here

    entry = LLMLogEntry(
        request_id      = str(uuid.uuid4()),
        timestamp       = (sim_start + timedelta(hours=i*0.5)).isoformat(),
        prompt_version  = PROMPT_CFG['version'],
        prompt_hash     = hash_prompt(PROMPT_CFG['system'], PROMPT_CFG['user_template']),
        model           = PRODUCTION_MODEL,
        task_type       = 'credit_memo',
        borrower_id     = f'BRW-{i+1:04d}',
        input_tokens    = result['input_tokens'],
        output_tokens   = result['output_tokens'],
        latency_ms      = result['latency_ms'],
        cost_usd        = result['cost'],
        output_text     = result['output'],
        output_word_count = len(result['output'].split()),
        environment     = 'simulation',
    )
    log_entry(conn, entry)
    time.sleep(0.1)

count = conn.execute('SELECT COUNT(*) FROM llm_logs').fetchone()[0]
print(f'\n✅ {count} log entries written to SQLite')

# Re-execute v1.0 simulation with tracing
print('Running v1.0 simulation with LangSmith tracing...')

SIMULATE_N = 10   # ← Change to 50 for full simulation
PROMPT_CFG = PROMPT_V1_0  # Baseline prompt

sim_start = datetime(2025, 6, 1, 9, 0, 0)

for i, borrower_data in enumerate(tqdm(BORROWER_PROFILES[:SIMULATE_N], desc='v1.0 run (traced)')):
    result = traced_call_model_with_prompt(PROMPT_CFG, borrower_data)

    entry = LLMLogEntry(
        request_id      = str(uuid.uuid4()),
        timestamp       = (sim_start + timedelta(hours=i*0.5)).isoformat(),
        prompt_version  = PROMPT_CFG['version'],
        prompt_hash     = hash_prompt(PROMPT_CFG['system'], PROMPT_CFG['user_template']),
        model           = PRODUCTION_MODEL,
        task_type       = 'credit_memo',
        borrower_id     = f'BRW-{i+1:04d}',
        input_tokens    = result['input_tokens'],
        output_tokens   = result['output_tokens'],
        latency_ms      = result['latency_ms'],
        cost_usd        = result['cost'],
        output_text     = result['output'],
        output_word_count = len(result['output'].split()),
        environment     = 'simulation',
    )
    log_entry(conn, entry)
    time.sleep(0.1)

count = conn.execute('SELECT COUNT(*) FROM llm_logs').fetchone()[0]
print(f'\n✅ {count} log entries written to SQLite (v1.0 traced)')

"""Step 4 — Run Automated Quality Probes"""

# ── Quality probe suite ───────────────────────────────────────────────

REQUIRED_SECTIONS = [
    'borrower',    # Must mention borrower name or overview
    'financial',   # Must mention financial figures
    'risk',        # Must contain risk assessment
    'recommend',   # Must contain a recommendation
]


def probe_hallucination(borrower_data: str, output: str) -> tuple:
    """Check for numeric hallucination (values in output not in source)."""
    def extract_nums(text):
        raw  = re.findall(r'\$?[\d,]+\.?\d*[KMB]?', text)
        nums = set()
        for r in raw:
            r_clean = r.replace('$','').replace(',','')
            try:
                if r_clean.endswith('K'):   nums.add(float(r_clean[:-1]) * 1e3)
                elif r_clean.endswith('M'): nums.add(float(r_clean[:-1]) * 1e6)
                elif r_clean.endswith('B'): nums.add(float(r_clean[:-1]) * 1e9)
                else:                        nums.add(float(r_clean))
            except: pass
        return nums

    source_nums = extract_nums(borrower_data)
    output_nums = extract_nums(output)

    hallucinated = [
        v for v in output_nums
        if v > 1000  # Only flag substantial figures
        and not any(abs(v - s) / max(s, 0.01) < 0.05 for s in source_nums if s > 0)
    ]
    return len(hallucinated) > 0, len(hallucinated)


def probe_missing_sections(output: str) -> list:
    """Detect which required sections are absent."""
    output_lower = output.lower()
    return [s for s in REQUIRED_SECTIONS if s not in output_lower]


def probe_output_length(output: str) -> bool:
    """Flag outputs outside the 150-250 word target range."""
    wc = len(output.split())
    return wc < 100 or wc > 350


def simulate_user_correction(output: str, borrower_data: str) -> bool:
    """Simulate analyst feedback: ~60% chance of flagging if output has issues."""
    has_issue = (probe_missing_sections(output) or
                 probe_hallucination(borrower_data, output)[0] or
                 probe_output_length(output))
    return has_issue and random.random() < 0.6


# ── Apply probes to all logged entries ────────────────────────────
df_logs = pd.read_sql('SELECT * FROM llm_logs', conn)

for idx, row in df_logs.iterrows():
    if not row['output_text']: continue

    borrower_data = BORROWER_PROFILES[int(row['borrower_id'].split('-')[1]) - 1]
    hall_flag, hall_count = probe_hallucination(borrower_data, row['output_text'])
    missing    = probe_missing_sections(row['output_text'])
    correction = simulate_user_correction(row['output_text'], borrower_data)
    length_vio = probe_output_length(row['output_text'])

    # Categorise failure
    if hall_flag:        cat = 'hallucination'
    elif missing:        cat = 'missing_sections'
    elif length_vio:     cat = 'length_violation'
    elif correction:     cat = 'analyst_correction'
    else:                cat = None

    # Update in-memory dataframe
    df_logs.at[idx, 'hallucination_flag']  = int(hall_flag)
    df_logs.at[idx, 'hallucination_count'] = hall_count
    df_logs.at[idx, 'missing_sections']    = json.dumps(missing)
    df_logs.at[idx, 'user_correction']     = int(correction)
    df_logs.at[idx, 'failure_category']    = cat

    # Persist to SQLite
    conn.execute('''UPDATE llm_logs SET
        hallucination_flag=?, hallucination_count=?,
        missing_sections=?, user_correction=?, failure_category=?
        WHERE request_id=?''',
        (int(hall_flag), hall_count, json.dumps(missing),
         int(correction), cat, row['request_id']))

conn.commit()

print('✅ Quality probes applied')
print(f'   Total entries: {len(df_logs)}')
print(f'   Failures: {df_logs["failure_category"].notna().sum()} '
      f'({df_logs["failure_category"].notna().mean()*100:.0f}%)')
print(f'\nFailure breakdown:')
print(df_logs['failure_category'].value_counts(dropna=False))

# Re-apply probes to all logged entries (including new traced ones)

df_logs = pd.read_sql('SELECT * FROM llm_logs', conn)

for idx, row in df_logs.iterrows():
    if not row['output_text']: continue

    # Ensure borrower_id is valid for indexing BORROWER_PROFILES
    borrower_idx_str = row['borrower_id'].split('-')[1]
    borrower_idx = int(borrower_idx_str) - 1
    if 0 <= borrower_idx < len(BORROWER_PROFILES):
        borrower_data = BORROWER_PROFILES[borrower_idx]
    else:
        print(f"Warning: Invalid borrower_id '{row['borrower_id']}' at index {idx}. Skipping probe for this entry.")
        continue

    hall_flag, hall_count = probe_hallucination(borrower_data, row['output_text'])
    missing    = probe_missing_sections(row['output_text'])
    correction = simulate_user_correction(row['output_text'], borrower_data)
    length_vio = probe_output_length(row['output_text'])

    # Categorise failure
    if hall_flag:        cat = 'hallucination'
    elif missing:        cat = 'missing_sections'
    elif length_vio:     cat = 'length_violation'
    elif correction:     cat = 'analyst_correction'
    else:                cat = None

    # Update in-memory dataframe
    df_logs.at[idx, 'hallucination_flag']  = int(hall_flag)
    df_logs.at[idx, 'hallucination_count'] = hall_count
    df_logs.at[idx, 'missing_sections']    = json.dumps(missing)
    df_logs.at[idx, 'user_correction']     = int(correction)
    df_logs.at[idx, 'failure_category']    = cat

    # Persist to SQLite
    conn.execute('''UPDATE llm_logs SET
        hallucination_flag=?, hallucination_count=?,
        missing_sections=?, user_correction=?, failure_category=?
        WHERE request_id=?''',
        (int(hall_flag), hall_count, json.dumps(missing),
         int(correction), cat, row['request_id']))

conn.commit()

print('✅ Quality probes re-applied to all logs')

"""Step 5 — Failure Triage"""

# ── Analyse failure patterns ─────────────────────────────────────────
df_logs = pd.read_sql('SELECT * FROM llm_logs', conn)

failures = df_logs[df_logs['failure_category'].notna()].copy()

print(f'\n📊 FAILURE TRIAGE REPORT — Prompt {PROMPT_V1_0["version"]}')
print('=' * 60)
print(f'Total requests:   {len(df_logs)}')
print(f'Failures:         {len(failures)} ({len(failures)/len(df_logs)*100:.0f}%)')
print(f'\nFailure categories:')
print(failures['failure_category'].value_counts().to_string())

print(f'\n📋 Sample failing outputs (worst first by hallucination):')
worst = df_logs.sort_values('hallucination_count', ascending=False).head(3)
for _, row in worst.iterrows():
    if row['output_text']:
        print(f'\n  borrower_id: {row["borrower_id"]} | failure: {row["failure_category"]}')
        print(f'  Output preview: {row["output_text"][:200]}...')

# Re-run failure triage
df_logs = pd.read_sql('SELECT * FROM llm_logs', conn)

failures = df_logs[df_logs['failure_category'].notna()].copy()

print(f'\n📊 FAILURE TRIAGE REPORT — ALL PROMPTS (Traced)')
print('=' * 60)
print(f'Total requests:   {len(df_logs)}')
print(f'Failures:         {len(failures)} ({len(failures)/len(df_logs)*100:.0f}%)')
print(f'\nFailure categories:')
print(failures['failure_category'].value_counts().to_string())

print(f'\n📋 Sample failing outputs (worst first by hallucination):')
worst = df_logs.sort_values('hallucination_count', ascending=False).head(3)
for _, row in worst.iterrows():
    if row['output_text']:
        print(f'\n  borrower_id: {row["borrower_id"]} | failure: {row["failure_category"]}')
        print(f'  Output preview: {row["output_text"][:200]}...')

print('✅ Failure triage updated')

"""Step 6 — Inspect Worst Performers"""

# ── Deep-dive into highest-hallucination outputs ─────────────────────
print('\n🔍 WORST PERFORMERS — Hallucination Deep-Dive')
print('=' * 60)

worst_5 = df_logs.sort_values('hallucination_count', ascending=False).head(5)

for _, row in worst_5.iterrows():
    if not row['output_text']: continue
    borrower_data = BORROWER_PROFILES[int(row['borrower_id'].split('-')[1]) - 1]
    print(f'\n📋 Request: {row["request_id"][:8]}... | Borrower: {row["borrower_id"]}')
    print(f'   Hallucination count: {row["hallucination_count"]}')
    print(f'   Missing sections: {row["missing_sections"]}')
    print(f'   Word count: {row["output_word_count"]}')
    print(f'   Latency: {row["latency_ms"]:.0f}ms | Cost: ${row["cost_usd"]:.6f}')
    print(f'\n   BORROWER DATA: {borrower_data[:150]}...')
    print(f'   MODEL OUTPUT:  {row["output_text"][:300]}...')

# ── Identify root cause ──────────────────────────────────────────
print('\n\n🔑 ROOT CAUSE ANALYSIS')
print('The v1.0 prompt provides no structural guidance or anti-hallucination rules.')
print('This causes models to:')
print('  1. Fill in missing data with plausible-sounding fabricated numbers')
print('  2. Skip required sections (no template enforced)')
print('  3. Vary output length unpredictably')
print('\n→ Solution: upgrade to v2.0 with explicit structure and compliance rules.')

# Re-run worst performers deep-dive
print('\n🔍 WORST PERFORMERS — Hallucination Deep-Dive (Traced)')
print('=' * 60)

worst_5 = df_logs.sort_values('hallucination_count', ascending=False).head(5)

for _, row in worst_5.iterrows():
    if not row['output_text']: continue
    borrower_data = BORROWER_PROFILES[int(row['borrower_id'].split('-')[1]) - 1]
    print(f'\n📋 Request: {row["request_id"][:8]}... | Borrower: {row["borrower_id"]}')
    print(f'   Hallucination count: {row["hallucination_count"]}')
    print(f'   Missing sections: {row["missing_sections"]}')
    print(f'   Word count: {row["output_word_count"]}')
    print(f'   Latency: {row["latency_ms"]:.0f}ms | Cost: ${row["cost_usd"]:.6f}')
    print(f'\n   BORROWER DATA: {borrower_data[:150]}...')
    print(f'   MODEL OUTPUT:  {row["output_text"][:300]}...')

print('✅ Worst performers deep-dive updated')

"""Step 7 — Run v2.0 Prompt on Same Inputs"""

# ── Re-run the same 50 borrower profiles with the improved prompt ─────
print('Running v2.0 prompt on same inputs...')

PROMPT_CFG_V2 = PROMPT_V2_0

for i, borrower_data in enumerate(tqdm(BORROWER_PROFILES[:SIMULATE_N], desc='v2.0 run')):
    result = traced_call_model_with_prompt(PROMPT_CFG_V2, borrower_data)

    hall_flag, hall_count = probe_hallucination(borrower_data, result['output'])
    missing    = probe_missing_sections(result['output'])
    correction = simulate_user_correction(result['output'], borrower_data)
    length_vio = probe_output_length(result['output'])

    if hall_flag:        cat = 'hallucination'
    elif missing:        cat = 'missing_sections'
    elif length_vio:     cat = 'length_violation'
    elif correction:     cat = 'analyst_correction'
    else:                cat = None

    entry = LLMLogEntry(
        request_id      = str(uuid.uuid4()),
        timestamp       = (sim_start + timedelta(hours=i*0.5 + 100)).isoformat(),
        prompt_version  = PROMPT_CFG_V2['version'],
        prompt_hash     = hash_prompt(PROMPT_CFG_V2['system'], PROMPT_CFG_V2['user_template']),
        model           = PRODUCTION_MODEL,
        task_type       = 'credit_memo',
        borrower_id     = f'BRW-{i+1:04d}',
        input_tokens    = result['input_tokens'],
        output_tokens   = result['output_tokens'],
        latency_ms      = result['latency_ms'],
        cost_usd        = result['cost'],
        output_text     = result['output'],
        output_word_count = len(result['output'].split()),
        environment     = 'simulation',
    )

    entry.hallucination_flag  = hall_flag
    entry.hallucination_count = hall_count
    entry.missing_sections    = json.dumps(missing)
    entry.user_correction     = correction
    entry.failure_category    = cat

    log_entry(conn, entry)
    time.sleep(0.1)

print('✅ v2.0 run complete')

# Re-execute v2.0 simulation with tracing
print('Running v2.0 simulation with LangSmith tracing...')

PROMPT_CFG_V2 = PROMPT_V2_0

for i, borrower_data in enumerate(tqdm(BORROWER_PROFILES[:SIMULATE_N], desc='v2.0 run (traced)')):
    result = traced_call_model_with_prompt(PROMPT_CFG_V2, borrower_data)

    hall_flag, hall_count = probe_hallucination(borrower_data, result['output'])
    missing    = probe_missing_sections(result['output'])
    correction = simulate_user_correction(result['output'], borrower_data)
    length_vio = probe_output_length(result['output'])

    if hall_flag:        cat = 'hallucination'
    elif missing:        cat = 'missing_sections'
    elif length_vio:     cat = 'length_violation'
    elif correction:     cat = 'analyst_correction'
    else:                cat = None

    entry = LLMLogEntry(
        request_id      = str(uuid.uuid4()),
        timestamp       = (sim_start + timedelta(hours=i*0.5 + 100)).isoformat(),
        prompt_version  = PROMPT_CFG_V2['version'],
        prompt_hash     = hash_prompt(PROMPT_CFG_V2['system'], PROMPT_CFG_V2['user_template']),
        model           = PRODUCTION_MODEL,
        task_type       = 'credit_memo',
        borrower_id     = f'BRW-{i+1:04d}',
        input_tokens    = result['input_tokens'],
        output_tokens   = result['output_tokens'],
        latency_ms      = result['latency_ms'],
        cost_usd        = result['cost'],
        output_text     = result['output'],
        output_word_count = len(result['output'].split()),
        environment     = 'simulation',
    )

    entry.hallucination_flag  = hall_flag
    entry.hallucination_count = hall_count
    entry.missing_sections    = json.dumps(missing)
    entry.user_correction     = correction
    entry.failure_category    = cat

    log_entry(conn, entry)
    time.sleep(0.1)

print('✅ v2.0 run complete (traced)')

"""Step 8 — Before/After Comparison Dashboard"""

df_all = pd.read_sql('SELECT * FROM llm_logs', conn)

# ── Compute metrics per prompt version ───────────────────────────
comparison = df_all.groupby('prompt_version').agg(
    n_requests       = ('request_id',         'count'),
    hallucin_rate    = ('hallucination_flag',  'mean'),
    missing_sec_rate = ('missing_sections',    lambda x: (x != '[]').mean()),
    user_correction  = ('user_correction',     'mean'),
    avg_latency_ms   = ('latency_ms',          'mean'),
    avg_cost         = ('cost_usd',            'mean'),
    avg_word_count   = ('output_word_count',   'mean'),
    failure_rate     = ('failure_category',    lambda x: x.notna().mean()),
).round(4).reset_index()

comparison = comparison[comparison['prompt_version'].isin(['v1.0', 'v2.0'])]

# Fill NaN values in the metrics columns with 0 before plotting
metrics_to_fill_na = ['hallucin_rate', 'missing_sec_rate', 'user_correction', 'failure_rate']
comparison[metrics_to_fill_na] = comparison[metrics_to_fill_na].fillna(0)

print('\n📊 BEFORE / AFTER PROMPT COMPARISON')
print('=' * 70)
print(comparison[['prompt_version','hallucin_rate','missing_sec_rate',
                  'user_correction','failure_rate','avg_cost']].to_string(index=False))

# ── Visualize Failure Rate ────────────────────────────────────────
if len(comparison) >= 2:
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.barplot(x='prompt_version', y='failure_rate', data=comparison, palette=['#F97316', '#0D9488'], ax=ax)
    ax.set_title(f'Overall Failure Rate: v1.0 vs v2.0 (Groq: {PRODUCTION_MODEL})', fontsize=13, fontweight='bold')
    ax.set_xlabel('Prompt Version')
    ax.set_ylabel('Failure Rate (%)')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y*100:.1f}%')) # Format as percentage

    # Add percentage labels on top of bars
    for container in ax.containers:
        ax.bar_label(container, fmt='%.1f%%')

    plt.tight_layout()
    plt.savefig('failure_rate_comparison_groq.png', dpi=150, bbox_inches='tight')
    plt.show()

print('✅ Failure rate chart saved: failure_rate_comparison_groq.png')

# Regenerate comparison dashboard after all simulations and probes

df_all = pd.read_sql('SELECT * FROM llm_logs', conn)

# ── Compute metrics per prompt version ───────────────────────────
comparison = df_all.groupby('prompt_version').agg(
    n_requests       = ('request_id',         'count'),
    hallucin_rate    = ('hallucination_flag',  'mean'),
    missing_sec_rate = ('missing_sections',    lambda x: (x != '[]').mean()),
    user_correction  = ('user_correction',     'mean'),
    avg_latency_ms   = ('latency_ms',          'mean'),
    avg_cost         = ('cost_usd',            'mean'),
    avg_word_count   = ('output_word_count',   'mean'),
    failure_rate     = ('failure_category',    lambda x: x.notna().mean()),
).round(4).reset_index()

comparison = comparison[comparison['prompt_version'].isin(['v1.0', 'v2.0'])]

# Fill NaN values in the metrics columns with 0 before plotting
metrics_to_fill_na = ['hallucin_rate', 'missing_sec_rate', 'user_correction', 'failure_rate']
comparison[metrics_to_fill_na] = comparison[metrics_to_fill_na].fillna(0)

print('\n📊 BEFORE / AFTER PROMPT COMPARISON (Traced)')
print('=' * 70)
print(comparison[['prompt_version','hallucin_rate','missing_sec_rate',
                  'user_correction','failure_rate','avg_cost']].to_string(index=False))

# ── Visualize Failure Rate ────────────────────────────────────────
if len(comparison) >= 2:
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.barplot(x='prompt_version', y='failure_rate', data=comparison, palette=['#F97316', '#0D9488'], ax=ax)
    ax.set_title(f'Overall Failure Rate: v1.0 vs v2.0 (Groq: {PRODUCTION_MODEL}) (Traced)', fontsize=13, fontweight='bold')
    ax.set_xlabel('Prompt Version')
    ax.set_ylabel('Failure Rate (%)')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y*100:.1f}%')) # Format as percentage

    # Add percentage labels on top of bars
    for container in ax.containers:
        ax.bar_label(container, fmt='%.1f%%')

    plt.tight_layout()
    plt.savefig('failure_rate_comparison_groq_traced.png', dpi=150, bbox_inches='tight')
    plt.show()

print('✅ Failure rate chart saved: failure_rate_comparison_groq_traced.png')

print('\nAll simulations and analyses have been re-run with LangSmith tracing enabled.')
print('You can view your traces at: https://smith.langchain.com')

import sqlite3
import pandas as pd

# Re-establish connection to ensure we read from the correct, updated DB
conn = sqlite3.connect('finsight_logs_groq.db')

df_all = pd.read_sql('SELECT * FROM llm_logs', conn)

# ── Compute metrics per prompt version ───────────────────────────
comparison = df_all.groupby('prompt_version').agg(
    n_requests       = ('request_id',         'count'),
    hallucin_rate    = ('hallucination_flag',  'mean'),
    missing_sec_rate = ('missing_sections',    lambda x: (x != '[]').mean()),
    user_correction  = ('user_correction',     'mean'),
    avg_latency_ms   = ('latency_ms',          'mean'),
    avg_cost         = ('cost_usd',            'mean'),
    avg_word_count   = ('output_word_count',   'mean'),
    failure_rate     = ('failure_category',    lambda x: x.notna().mean()),
).round(4).reset_index()

comparison = comparison[comparison['prompt_version'].isin(['v1.0', 'v2.0'])]

# Fill NaN values in the metrics columns with 0 (important for consistency)
metrics_to_fill_na = ['hallucin_rate', 'missing_sec_rate', 'user_correction', 'failure_rate']
comparison[metrics_to_fill_na] = comparison[metrics_to_fill_na].fillna(0)

# Check if comparison DataFrame has enough data after filtering
if 'v1.0' not in comparison['prompt_version'].values or 'v2.0' not in comparison['prompt_version'].values:
    print("Error: Could not find data for both 'v1.0' and 'v2.0' in the database.")
    print("Please ensure that the simulation cells (v1.0 and v2.0) were executed successfully to populate the database.")
else:
    v1_latency = comparison[comparison['prompt_version'] == 'v1.0']['avg_latency_ms'].iloc[0]
    v2_latency = comparison[comparison['prompt_version'] == 'v2.0']['avg_latency_ms'].iloc[0]

    latency_improvement = v1_latency - v2_latency

    print(f"Average Latency for v1.0: {v1_latency:.2f} ms")
    print(f"Average Latency for v2.0: {v2_latency:.2f} ms")
    print(f"Latency Improvement (v1.0 - v2.0): {latency_improvement:.2f} ms")

failed_entries = df_all[df_all['failure_category'].notna()]
display(failed_entries)

"""9.REFLECTION QUESTIONS

**Which failure category had the highest business impact for FinSight? Why?**

In the context of credit risk analysis, hallucinations would have the highest business impact. Providing incorrect or fabricated financial figures, risk assessments, or recommendations could lead to severe financial losses, regulatory non-compliance, and reputational damage. While missing sections or user corrections are problematic, they typically result in rework or delayed decisions, whereas hallucinated data actively misleads. Given our limited simulation size and the current results showing 0% hallucination for both versions, this might not be fully reflected, but in a real-world scenario, hallucination is a critical failure.

**The v2.0 prompt is longer — does that mean higher cost? Look at your avg_cost comparison.**

Yes, generally, a longer prompt means higher input token count, which translates to a higher cost as Groq's pricing is per token. However, looking at the comparison table, both v1.0 and v2.0 show an avg_cost of 0.0. This is likely because the simulation results in the result dictionary had input_tokens and output_tokens as 0 due to the 'Invalid API Key' error mentioned earlier. In a real-world scenario with a valid API key, v2.0 would indeed incur a higher cost per call due to its increased prompt length compared to v1.0.

**If hallucination rate is still > 0% after v2.0, what would your next experiment be?**


If hallucinations persist, I would consider:
Adding more explicit negative constraints to the prompt: Reinforce instructions like "Do NOT invent information" or "Only use the exact numbers provided." Sometimes models need strong, explicit negative guidance.
Implementing an external validation step: After the memo is generated, run a programmatic check that extracts numbers from the output and compares them against the source borrower_data to flag any new, unverified numbers.
Leveraging few-shot examples: Provide a few examples within the prompt where the model successfully avoids hallucination, especially with tricky or incomplete data, and another example where it incorrectly hallucinates and how that was corrected. This can help the model learn the desired behavior.
Exploring Retrieval-Augmented Generation (RAG): If the expectation is that the model should pull some external, verified data (e.g., industry averages), integrating a RAG pipeline that retrieves information from trusted sources and feeds it to the LLM would be crucial.

How would you set up alerting so the team is notified within 1 hour if hallucination rate exceeds 2%?

I would implement a scheduled job (e.g., a daily cron job, a Cloud Scheduler/Cloud Function in GCP, or an Airflow DAG) that runs every hour. This job would:
Query the llm_logs SQLite database to fetch all log entries from the last hour.
Calculate the hallucination rate for these recent entries (i.e., SUM(hallucination_flag) / COUNT(*)).
If the calculated hallucination rate exceeds 2%, it would trigger an alert. This alert could be sent via email, a Slack notification, or integrated with an on-call system like PagerDuty. The alert message would include details like the current rate, the time period, and a link to a dashboard for deeper investigation.

**Groq delivers sub-second latency — what new product features does this enable for FinSight?**

Sub-second latency is a game-changer for FinSight, enabling several new features:
Real-time Interactive Memos: Analysts can converse with an AI assistant to dynamically refine credit memos, ask follow-up questions about risk factors, or explore different scenarios with immediate responses.
Instantaneous Pre-approvals/Initial Assessments: Automated systems could provide real-time loan pre-approvals or instant initial risk assessments for new applications, significantly speeding up the lending pipeline and improving customer experience.
Live Underwriting Support: During client meetings, an underwriter could input a few data points and get an immediate, AI-generated summary of potential risks and recommendations, enhancing decision-making on the fly.
High-Volume Batch Processing: For large portfolios, thousands of credit memos could be generated or updated in minutes, not hours, allowing for more frequent risk monitoring and proactive portfolio management.
Dynamic Document Generation: Rapid generation of various financial documents (e.g., term sheets, risk disclosures) tailored to specific borrower profiles almost instantly.

**🚀 Extension Task — LangSmith / Weights & Biases Integration
⏱ +10 minutes | Advanced participants**

Option A: LangSmith Tracing (Groq via OpenAI-compatible endpoint)
Install langsmith and langchain-groq
Set LANGCHAIN_TRACING_V2=true and LANGCHAIN_API_KEY in secrets
Wrap your call_model_with_prompt function with a LangSmith tracer
View traces in the LangSmith UI — compare v1.0 vs v2.0 side by side
"""

# ── EXTENSION A: LangSmith with Groq ──────────────────────────────────
!pip install langsmith langchain-groq -q

import os
from google.colab import userdata # Added this line
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_API_KEY']    = userdata.get('LANGCHAIN_API_KEY')
os.environ['LANGCHAIN_PROJECT']    = 'finsight-feedback-loop-groq'

from langsmith import traceable
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

@traceable(name='credit_memo_groq')
def call_with_tracing(prompt_cfg, borrower_data):
    # Removed explicit groq_api_key, relying on os.environ['GROQ_API_KEY'] set in mnkEBKwkmhTb
    llm = ChatGroq(model='llama-3.3-70b-versatile')
    messages = [
        SystemMessage(content=prompt_cfg['system']),
        HumanMessage(content=prompt_cfg['user_template'].format(data=borrower_data))
    ]
    return llm.invoke(messages).content

output = call_with_tracing(PROMPT_V2_0, BORROWER_PROFILES[0])
print('Traced output:', output[:200])
print('View traces at: https://smith.langchain.com')

"""**Option B: Weights & Biases**

1. Install wandb
2. Log each run as a W&B artifact: 3.3. prompt version, Groq model, metrics, outputs
4. Create a W&B Table comparing model outputs
5. Use W&B Sweeps to auto-tune temperature for minimum hallucination rate
"""

# ── EXTENSION B: Weights & Biases ─────────────────────────────────
!pip install wandb -q
import wandb
wandb.login(key=userdata.get('WANDB_API_KEY'))

run = wandb.init(project='finsight-prompt-eval-groq',
                 config={'model': PRODUCTION_MODEL, 'version': '2.0'})
table = wandb.Table(columns=['borrower_id','prompt_version','output','hallucination','failure_cat','cost_usd'])
for _, row in df_all.iterrows():
    table.add_data(row['borrower_id'], row['prompt_version'], row['output_text'][:200],
                   bool(row['hallucination_flag']), row['failure_category'], row['cost_usd'])
wandb.log({'results': table})
run.finish()