# -*- coding: utf-8 -*-
"""DAY4 (Joins and window function).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mv2saUGNgX1zQEpvVc3_sk9QgCLnSOmi

# JOINS AND WINDOW FUNCTIONS
"""

import pandas as pd
import sqlite3

def print_dataframe(dataframe):
  print(dataframe.to_string(index=False))

conn=sqlite3.connect(":memory:")
cursor=conn.cursor()

#1.Emp table
employees_data={
    "Emp_ID":[1,2,3,4],
    "Emp_Name":["Alice(CEO)","Bob (Manager)","Charlie (Dev)","David (Dev)"],
    "Manager_ID":[None,1,2,2]
}

#2.customers table
customers_data={
    "Customer_ID":[101,102,103,104],
    "Customer_Name":["Rajat","Sita","John","Amit"]
}

# Orders table
orders_data = {
    "Order_ID": [5100,5002,5003,5004],
    "Customer_ID": [101,102,101,999],
    "Amount":[250.00,45.50,120.00,89.99]}

# Form Factor matrix
products={"Product_Name":["Laptop","Phone"]}
colors={"Color":["Black","Sliver"]}

#Load dataframes to sql
pd.DataFrame(employees_data).to_sql("employees",conn,index=False)
pd.DataFrame(customers_data).to_sql("customers",conn,index=False)
pd.DataFrame(orders_data).to_sql("orders",conn,index=False)
pd.DataFrame(products).to_sql("products",conn,index=False)
pd.DataFrame(colors).to_sql("colors",conn,index=False)

print("Database initialized with tables: Employess,Customers,orders,products,colors")

print("--Inner Join--")
inner="""
SELECT c.Customer_ID,c.Customer_Name,o.Order_ID,o.Amount
FROM customers c
INNER JOIN orders o ON c.Customer_ID=o.Customer_ID;
"""
print_dataframe(pd.read_sql_query(inner,conn))

print("--Left Join--")
left="""
SELECT c.Customer_ID,c.Customer_Name,o.Order_ID,o.Amount
FROM customers c
LEFT JOIN orders o ON c.Customer_ID=o.Customer_ID;
"""
print_dataframe(pd.read_sql_query(left,conn))

print("--self Join--")
self="""
SELECT e1.Emp_Name AS Employee,e2.Emp_Name AS Manager
FROM employees e1
LEFT JOIN employees e2 ON e1.Manager_ID=e2.Emp_ID;
"""
print_dataframe(pd.read_sql_query(self,conn))

print("--cross-join---")
cross="""
SELECT p.Product_Name,c.Color
FROM Products p
CROSS JOIN colors c;
"""
print_dataframe(pd.read_sql_query(cross,conn))

build_table_customers=[
    {"ID":101,"Customer_Name":"Rajat"},
    {"ID":102,"Customer_Name":"Sita"},
    {"ID":103,"Customer_Name":"John"},
]

probe_table_orders=[
    {"Order_ID":5100,"Customer_ID":101,"Amount":250.00},
    {"Order_ID":5002,"Customer_ID":102,"Amount":45.50},
    {"Order_ID":5004,"Customer_ID":999,"Amount":89.99}
]

def physical_hash_join(build_source,probe_source,build_key,probe_key):
  hash_table={}
  print("Hashing Build source on key :'{build_key}'")
  for row in build_source:
    key=row[build_key]
    if key not in hash_table:
      hash_table[key]=[]
    hash_table[key].append(row)
    print(f"Hashed key {key} mapping to row: {row}")

  # phase2:probe phase streaming through larger table and checking against the hash bucket index
  joined_results=[]
  print(f"[Phase2:Probe] Streaming Probe source on key: '{probe_key}'")
  for probe_row in probe_source:
    match_key=probe_row[probe_key]
    print(f"Probe row: {match_key}..")
    if match_key in hash_table:
      print("[cache hit] matching records")
      for match_row in hash_table[match_key]:
        combined_row={**match_row,**probe_row}
        joined_results.append(combined_row)
    else:
      print("[cache miss] no matching records")
  print("Execution completed")
  return pd.DataFrame(joined_results)

df_hash_join_output=physical_hash_join(build_table_customers,probe_table_orders,"ID","Customer_ID")
print_dataframe(df_hash_join_output)

# Execute Setup to instantitate data contexts
servers_inventory={
    "Host_ID":["SRV-01","SRV-02","SRV-03"],
    "Role":["Web Front","Api Gateway", "Database Replica"]
}
live_interfaces={
    "Interface_ID":["eth0","eth1"],
    "Mapped_host":["SRV-01","SRV-02"],
    "IP_Address":["10.0.0.4","10.0.0.9"]
}

df_srv=pd.DataFrame(servers_inventory)
df_inf=pd.DataFrame(live_interfaces)

df_srv.to_sql("servers",conn,index=False,if_exists="replace")
df_inf.to_sql("interfaces",conn,index=False,if_exists="replace")

# Broken Query framework
fault_query="""
SELECT s.Host_ID,s.Role,i.Interface_ID,i.IP_Address
FROM servers s
INNER JOIN interfaces i ON s.Host_ID=i.Mapped_host;
"""

print("--Faulty output metrics--")
print_dataframe(pd.read_sql_query(fault_query,conn))

"""1. Explain why SRV-03 is excluded from the query framework above based on the mechanics of a INNER JOIN

2. Rewrite the query below to implement a join strategy that outputs all server configuration from inventory, regardless of wheather they have live network interface.
"""

# Inner join returns only rows with matching values in both tables.
# SRV-03 has no matching record in interfaces, so it is excluded.

# Left Join returns all records from servers and matching records
# from interfaces unmatched servers Show NULL Values.

Query="""
SELECT s.Host_ID,s.Role,i.Interface_ID,i.IP_Address
FROM servers s
LEFT JOIN interfaces i ON s.Host_ID=i.Mapped_host;
"""

print("--Correct output metrics--")
print_dataframe(pd.read_sql_query(Query,conn))

conn.close()