# -*- coding: utf-8 -*-
"""Langchain_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWMwNiTowUkqtPZcJZtnRnOyW071HDLB

#🧪 Day 16 Colab 2 — LangChain Agent with Short-Term & Long-Term Memory + Tools

Converted from Colab notebook to standalone Python script.
Uses OpenAI GPT-4o instead of Anthropic Claude.
Loads credentials from the project-level .env file.

Architecture:
  User Prompt → AgentExecutor (ReAct LLM + STM + Tools) → LTM (ChromaDB)

STM = rolling conversation window (this session)
LTM = semantic vector store (persists across sessions)
"""

import os
import sys
import time
import json
import math
import ast
import operator
import sqlite3

from dotenv import load_dotenv

# ─────────────────────────────────────────────────────────────────────────────
# Step 0 — Load Credentials from .env
# ─────────────────────────────────────────────────────────────────────────────

_env_path = os.path.join(os.path.dirname(__file__), "..", "..", ".env")
if os.path.exists(_env_path):
    load_dotenv(_env_path)
else:
    load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

if not OPENAI_API_KEY:
    print("❌ Missing OPENAI_API_KEY in .env file.")
    sys.exit(1)

# Set env vars so LangChain picks them up automatically
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
if TAVILY_API_KEY:
    os.environ["TAVILY_API_KEY"] = TAVILY_API_KEY

print("✅ Credentials loaded from .env")

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Initialize LLM (OpenAI GPT-4o)
# ─────────────────────────────────────────────────────────────────────────────

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0,
    max_tokens=2048,
)

print(f"✅ LLM ready: {llm.model_name}")

# ═══════════════════════════════════════════════════════════════════════════════
# PART 1 — SHORT-TERM MEMORY (STM)
# ═══════════════════════════════════════════════════════════════════════════════
#
# Short-Term Memory lives in the LLM's context window.
# It keeps the current conversation history so the agent can refer back.
#
# Two STM strategies:
#   ConversationBufferMemory  → Keeps ALL messages verbatim (good for short sessions)
#   ConversationSummaryMemory → Summarises older exchanges to save tokens (production)
# ─────────────────────────────────────────────────────────────────────────────

from langchain_classic.memory import ConversationBufferMemory
from langchain_classic.chains import ConversationChain

stm = ConversationBufferMemory(
    memory_key="history",
    return_messages=True,
)

conv_chain = ConversationChain(llm=llm, memory=stm, verbose=True)

print("\n" + "=" * 60)
print("🧠 PART 1: Short-Term Memory (STM)")
print("=" * 60)

print("\n=== Turn 1 ===")
r1 = conv_chain.predict(input="Hi! My name is Alex and I'm an ML engineer.")
print(r1)

print("\n=== Turn 2 ===")
r2 = conv_chain.predict(input="What did I just tell you about myself?")
print(r2)

# Inspect STM buffer
print("\n📝 Messages in STM buffer:")
for msg in stm.chat_memory.messages:
    role = msg.__class__.__name__
    print(f"  [{role}] {msg.content[:120]}")

# ═══════════════════════════════════════════════════════════════════════════════
# PART 2 — LONG-TERM MEMORY (LTM) with ChromaDB
# ═══════════════════════════════════════════════════════════════════════════════
#
# LTM stores information in a vector database that persists across sessions.
# At each turn the agent:
#   1. Embeds the user's query
#   2. Retrieves the top-k most relevant past Q&A pairs
#   3. Injects them into the prompt as additional context
# ─────────────────────────────────────────────────────────────────────────────

from langchain_chroma import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_classic.memory import VectorStoreRetrieverMemory

print("\n" + "=" * 60)
print("📚 PART 2: Long-Term Memory (LTM) with ChromaDB")
print("=" * 60)

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={"device": "cpu"},
)

# Persistent Chroma vector store
chroma_dir = os.path.join(os.path.dirname(__file__), "chroma_ltm")
vectorstore = Chroma(
    collection_name="agent_ltm",
    embedding_function=embeddings,
    persist_directory=chroma_dir,
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

ltm = VectorStoreRetrieverMemory(
    retriever=retriever,
    memory_key="ltm_context",
    return_docs=False,
)

print(f"✅ LTM ready — collection: '{vectorstore._collection.name}'")
print(f"   Docs currently stored: {vectorstore._collection.count()}")

# Seed some long-term memories
seed_memories = [
    {"input": "What is the user's name?",          "output": "Alex"},
    {"input": "What does the user work on?",        "output": "Machine Learning engineering at a fintech startup"},
    {"input": "What stack does the user prefer?",   "output": "Python, PyTorch, LangChain, Postgres"},
    {"input": "What project is the user working on?",
     "output": "Building a RAG pipeline over internal financial documents"},
    {"input": "What LLM provider does the user prefer?",
     "output": "OpenAI GPT-4o for reasoning tasks, HuggingFace for embeddings"},
]

for mem in seed_memories:
    ltm.save_context({"input": mem["input"]}, {"output": mem["output"]})

print(f"✅ Seeded {len(seed_memories)} memories")
print(f"   Total docs in LTM: {vectorstore._collection.count()}")

# Test LTM retrieval
query = "What framework does Alex use for building AI systems?"
retrieved = ltm.load_memory_variables({"prompt": query})
print(f"\n🔍 Query: {query}")
print(f"   Retrieved LTM context:\n   {retrieved['ltm_context']}")

# ═══════════════════════════════════════════════════════════════════════════════
# PART 3 — DEFINING TOOLS
# ═══════════════════════════════════════════════════════════════════════════════
#
# Tools:
#   TavilySearch  → Real-time web search
#   PythonREPL    → Execute arbitrary Python code
#   Calculator    → Safe arithmetic evaluation
# ─────────────────────────────────────────────────────────────────────────────

from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_experimental.tools import PythonREPLTool
from langchain_core.tools import Tool

print("\n" + "=" * 60)
print("🔧 PART 3: Defining Tools")
print("=" * 60)

# Tool 1: Web Search
search_tool = TavilySearchResults(
    max_results=4,
    description=(
        "Search the web for real-time information. "
        "Use for current events, recent data, or anything beyond your training cutoff."
    ),
)

# Tool 2: Python REPL
python_tool = PythonREPLTool()
python_tool.description = (
    "Execute Python code in a sandboxed REPL. "
    "Use for calculations, data analysis, string manipulation, or any computation. "
    "Input must be valid Python. Print your results."
)

# Tool 3: Safe Calculator
def safe_calc(expression: str) -> str:
    """Evaluate a simple arithmetic expression safely (no exec/eval tricks)."""
    allowed_ops = {
        ast.Add: operator.add, ast.Sub: operator.sub,
        ast.Mult: operator.mul, ast.Div: operator.truediv,
        ast.Pow: operator.pow, ast.USub: operator.neg,
    }
    def _eval(node):
        if isinstance(node, ast.Constant):
            return node.n
        elif isinstance(node, ast.BinOp):
            return allowed_ops[type(node.op)](_eval(node.left), _eval(node.right))
        elif isinstance(node, ast.UnaryOp):
            return allowed_ops[type(node.op)](_eval(node.operand))
        else:
            raise ValueError(f"Unsupported expression: {ast.dump(node)}")
    try:
        tree = ast.parse(expression, mode="eval")
        result = _eval(tree.body)
        return str(round(result, 6))
    except Exception as e:
        return f"Error: {e}"

calculator_tool = Tool(
    name="Calculator",
    func=safe_calc,
    description=(
        "Evaluate arithmetic expressions: +, -, *, /, **. "
        "Input: a plain math expression like '(1200 * 1.15) / 12'. "
        "Use this for simple arithmetic; use PythonREPL for complex logic."
    ),
)

tools = [search_tool, python_tool, calculator_tool]
print(f"✅ {len(tools)} tools ready: {[t.name for t in tools]}")

# ═══════════════════════════════════════════════════════════════════════════════
# PART 4 — ASSEMBLING THE FULL AGENT (STM + LTM + Tools)
# ═══════════════════════════════════════════════════════════════════════════════
#
# Combines:
#   STM (ConversationBufferMemory)  → rolling conversation window
#   LTM (VectorStoreRetrieverMemory) → semantic recall from past sessions
#   Tools → search, code execution, calculator
#   ReAct agent loop
# ─────────────────────────────────────────────────────────────────────────────

from langchain_classic.agents import AgentExecutor, create_react_agent
from langchain_core.prompts import PromptTemplate

print("\n" + "=" * 60)
print("🤖 PART 4: Assembling the Full Agent")
print("=" * 60)

REACT_TEMPLATE = """You are a helpful, knowledgeable AI research assistant with access to tools.

### Long-Term Memory (from past sessions)
{ltm_context}

### Current Conversation (Short-Term Memory)
{history}

### Available Tools
{tools}

### Tool Names
{tool_names}

### Instructions
- Reason step-by-step using the format below
- Use tools when you need real-time data or computation
- Reference Long-Term Memory when relevant to personalise your response
- Be concise but thorough

### Format (STRICT — always follow this)
Question: the input question
Thought: what you need to do
Action: the tool name (must be one of [{tool_names}])
Action Input: the input to the tool
Observation: the tool result
... (repeat Thought/Action/Action Input/Observation as needed)
Thought: I now know the final answer
Final Answer: your complete response

Begin!

Question: {input}
Thought: {agent_scratchpad}
"""

prompt = PromptTemplate(
    input_variables=["input", "history", "ltm_context", "tools", "tool_names", "agent_scratchpad"],
    template=REACT_TEMPLATE,
)

print(f"✅ Custom ReAct prompt created")
print(f"   Input variables: {prompt.input_variables}")

# STM for this session
session_stm = ConversationBufferMemory(
    memory_key="history",
    return_messages=False,
    input_key="input",
    output_key="output",
)

# Build the ReAct agent
agent = create_react_agent(llm=llm, tools=tools, prompt=prompt)

# AgentExecutor wires it all together
executor = AgentExecutor(
    agent=agent,
    tools=tools,
    memory=session_stm,
    max_iterations=8,
    handle_parsing_errors=True,
    verbose=True,
    return_intermediate_steps=True,
)

print("✅ AgentExecutor ready")
print(f"   Max iterations: {executor.max_iterations}")


# ── Helper: inject LTM context before each run ──────────────────────────────
def run_agent(user_input: str, show_steps: bool = False) -> str:
    """
    Run the agent with both STM (auto) and LTM (injected from Chroma).
    """
    # 1. Retrieve relevant LTM context for this query
    ltm_vars = ltm.load_memory_variables({"prompt": user_input})
    ltm_context = ltm_vars.get("ltm_context", "No relevant past context found.")

    # 2. Run the agent
    result = executor.invoke({
        "input": user_input,
        "ltm_context": ltm_context,
    })

    # 3. Save this exchange to LTM for future sessions
    ltm.save_context(
        {"input": user_input},
        {"output": result["output"]},
    )

    # 4. Optional: show intermediate steps
    if show_steps and "intermediate_steps" in result:
        print("\n📋 Tool calls made:")
        for action, observation in result["intermediate_steps"]:
            print(f"  🔧 {action.tool}({action.tool_input!r})")
            print(f"     → {str(observation)[:200]}")

    return result["output"]

print("✅ run_agent() helper ready")

# ═══════════════════════════════════════════════════════════════════════════════
# PART 5 — TEST THE AGENT
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("🧪 PART 5: Testing the Agent")
print("=" * 60)

# ── Test 1: Personalised response using LTM ─────────────────────────────────
print("\n" + "=" * 55)
print("TEST 1: Does the agent remember who it's talking to?")
print("=" * 55)

answer = run_agent(
    "What AI framework should I use for my project?",
    show_steps=True
)
print("\n🤖 Final Answer:")
print(answer)

# ── Test 2: Multi-step with web search + calculation ────────────────────────
print("\n" + "=" * 55)
print("TEST 2: Web search + arithmetic in one task")
print("=" * 55)

answer = run_agent(
    "What is the current population of India? "
    "Calculate what 0.5% of that would be, and convert to millions.",
    show_steps=True
)
print("\n🤖 Final Answer:")
print(answer)

# ── Test 3: STM in action — follow-up question ─────────────────────────────
print("\n" + "=" * 55)
print("TEST 3: Follow-up using STM (no re-stating context)")
print("=" * 55)

run_agent("Tell me about the latest developments in transformer architectures.")
answer = run_agent("Which of those would be most relevant to my work?")

print("\n🤖 Final Answer:")
print(answer)

# ── Test 4: Python REPL for data analysis ───────────────────────────────────
print("\n" + "=" * 55)
print("TEST 4: Agent writes and runs Python code")
print("=" * 55)

answer = run_agent(
    "Generate a list of the first 10 Fibonacci numbers, "
    "compute their sum, and tell me what percentage each number "
    "contributes to the total.",
    show_steps=True
)
print("\n🤖 Final Answer:")
print(answer)

# ── Inspect STM after 4 turns ────────────────────────────────────────────────
print("\n📝 Current STM buffer (last 4+ turns):")
history_str = session_stm.load_memory_variables({})["history"]
print(history_str[:2000])
print(f"\n📚 LTM now contains {vectorstore._collection.count()} documents")

# ═══════════════════════════════════════════════════════════════════════════════
# PART 6 — STM vs LTM Comparison
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("🔬 PART 6: STM vs LTM Comparison")
print("=" * 60)

stm_history = session_stm.load_memory_variables({})["history"]
test_query = "What programming languages does Alex use?"
ltm_result = ltm.load_memory_variables({"prompt": test_query})["ltm_context"]

print(f"""
┌─────────────────────────────────────────────────────────┐
│  SHORT-TERM MEMORY (this session)                       │
│  Messages: {len(session_stm.chat_memory.messages):>3} messages from current conversation     │
│  Persistence: Lost on session end                       │
│  Retrieval: Sequential (all messages)                   │
├─────────────────────────────────────────────────────────┤
│  LONG-TERM MEMORY (Chroma — persists across sessions)   │
│  Total docs: {vectorstore._collection.count():>3}                                        │
│  Retrieval: Semantic similarity search                  │
│  Query: "{test_query}"              │
│  Retrieved: {ltm_result[:50]}...    │
└─────────────────────────────────────────────────────────┘
""")

# ═══════════════════════════════════════════════════════════════════════════════
# EXTENSION 1 — ConversationSummaryMemory
# ═══════════════════════════════════════════════════════════════════════════════

from langchain_classic.memory import ConversationSummaryMemory

print("\n" + "=" * 60)
print("⚡ EXTENSION 1: ConversationSummaryMemory")
print("=" * 60)

summary_stm = ConversationSummaryMemory(
    llm=llm,
    memory_key="history",
    return_messages=False,
    input_key="input",
    output_key="output",
    human_prefix="User",
    ai_prefix="Agent",
)

summary_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    memory=summary_stm,
    max_iterations=8,
    handle_parsing_errors=True,
    verbose=False,
    return_intermediate_steps=False,
)

def run_agent_summary(user_input: str) -> str:
    ltm_vars = ltm.load_memory_variables({"prompt": user_input})
    result = summary_executor.invoke({
        "input": user_input,
        "ltm_context": ltm_vars.get("ltm_context", ""),
    })
    return result["output"]

for turn in [
    "Tell me about the history of neural networks.",
    "What were the key innovations in the 2010s?",
    "How did attention mechanisms change everything?",
    "What should I read to go deeper on this?",
]:
    print(f"\n  💬 User: {turn}")
    ans = run_agent_summary(turn)
    print(f"  🤖 Agent: {ans[:200]}...")

print("\n📝 Running conversation summary (STM):")
print(summary_stm.moving_summary_buffer or "(no summary yet — buffer not full)")
print(f"\nMessages still in buffer: {len(summary_stm.chat_memory.messages)}")

# ═══════════════════════════════════════════════════════════════════════════════
# EXTENSION 2 — SQLite Tool (Structured LTM)
# ═══════════════════════════════════════════════════════════════════════════════

from langchain_core.tools import StructuredTool
from pydantic import BaseModel

print("\n" + "=" * 60)
print("⚡ EXTENSION 2: SQLite as Structured LTM")
print("=" * 60)

conn = sqlite3.connect(":memory:")
cur = conn.cursor()

cur.executescript("""
    CREATE TABLE IF NOT EXISTS user_preferences (
        id INTEGER PRIMARY KEY,
        category TEXT,
        key TEXT,
        value TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO user_preferences (category, key, value) VALUES
        ('tools',    'preferred_llm',       'OpenAI GPT-4o'),
        ('tools',    'preferred_framework', 'LangChain + LangGraph'),
        ('project',  'name',                'FinDoc RAG Pipeline'),
        ('project',  'tech_stack',          'Python, Chroma, FastAPI'),
        ('project',  'deadline',            '2025-09-30');
""")
conn.commit()


class SQLQueryInput(BaseModel):
    query: str


def run_sql(query: str) -> str:
    """Run a read-only SQL query against the user preferences DB."""
    try:
        if not query.strip().upper().startswith("SELECT"):
            return "Error: only SELECT queries are allowed."
        rows = cur.execute(query).fetchall()
        cols = [d[0] for d in cur.description]
        if not rows:
            return "No results found."
        return json.dumps([dict(zip(cols, row)) for row in rows], indent=2)
    except Exception as e:
        return f"SQL Error: {e}"


sql_tool = StructuredTool.from_function(
    func=run_sql,
    name="UserPreferencesDB",
    description=(
        "Query the user's structured preference database using SQL SELECT statements. "
        "Table: user_preferences(id, category, key, value, created_at). "
        "Use this to look up exact user settings, project details, or tool preferences."
    ),
    args_schema=SQLQueryInput,
)

extended_tools = [search_tool, python_tool, calculator_tool, sql_tool]

ext_agent = create_react_agent(llm=llm, tools=extended_tools, prompt=prompt)
ext_executor = AgentExecutor(
    agent=ext_agent,
    tools=extended_tools,
    memory=ConversationBufferMemory(
        memory_key="history", return_messages=False,
        input_key="input", output_key="output"
    ),
    max_iterations=8,
    handle_parsing_errors=True,
    verbose=True,
)


def run_ext(q):
    ltm_ctx = ltm.load_memory_variables({"prompt": q}).get("ltm_context", "")
    return ext_executor.invoke({"input": q, "ltm_context": ltm_ctx})["output"]


print(run_ext("What framework am I using and when is my project deadline?"))

# ═══════════════════════════════════════════════════════════════════════════════
# EXTENSION 3 — Self-Critique Loop (Reflexion Pattern)
# ═══════════════════════════════════════════════════════════════════════════════

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

print("\n" + "=" * 60)
print("⚡ EXTENSION 3: Self-Critique Loop (Reflexion)")
print("=" * 60)

critic_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a rigorous AI quality reviewer.

Given a question and an agent's answer, provide:
1. A score from 1-10 (10 = perfect)
2. Specific weaknesses (missing facts, logic errors, unclear language)
3. A concrete suggestion for improvement

Format:
SCORE: <number>
WEAKNESSES: <bullet points>
SUGGESTION: <one clear improvement instruction>
"""),
    ("human", "Question: {question}\n\nAnswer: {answer}"),
])

revision_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a precise AI assistant. Revise the answer based on the feedback provided."),
    ("human", "Original question: {question}\n\nOriginal answer: {answer}\n\nCritic feedback: {critique}\n\nRevised answer:"),
])

critic_chain = critic_prompt | llm | StrOutputParser()
revision_chain = revision_prompt | llm | StrOutputParser()


def reflexion_run(question: str, max_rounds: int = 2) -> dict:
    """Run the agent, then apply self-critique rounds."""
    print(f"\n{'=' * 55}")
    print(f"Question: {question}")
    print("=" * 55)

    # Initial answer from the agent
    ltm_ctx = ltm.load_memory_variables({"prompt": question}).get("ltm_context", "")
    initial = executor.invoke({"input": question, "ltm_context": ltm_ctx})["output"]
    print(f"\n[Round 0 — Initial Answer]\n{initial}")

    current_answer = initial
    history = [{"round": 0, "answer": initial, "score": None, "critique": None}]

    for rnd in range(1, max_rounds + 1):
        # Critique
        critique = critic_chain.invoke({"question": question, "answer": current_answer})
        score_line = [l for l in critique.split("\n") if l.startswith("SCORE:")]
        score = int(score_line[0].split(":")[1].strip()) if score_line else 0
        print(f"\n[Round {rnd} — Critique] Score: {score}/10")
        print(critique)

        if score >= 9:
            print("\n✅ Score threshold reached — stopping early.")
            break

        # Revise
        current_answer = revision_chain.invoke({
            "question": question,
            "answer": current_answer,
            "critique": critique,
        })
        print(f"\n[Round {rnd} — Revised Answer]\n{current_answer}")
        history.append({"round": rnd, "answer": current_answer, "score": score, "critique": critique})

    return {"final_answer": current_answer, "history": history}


result = reflexion_run(
    "What are the main risks of using LLM-based agents in production financial systems?",
    max_rounds=2,
)

# ═══════════════════════════════════════════════════════════════════════════════
# EXTENSION 4 — Streaming Agent Output
# ═══════════════════════════════════════════════════════════════════════════════

from langchain_core.callbacks import BaseCallbackHandler

print("\n" + "=" * 60)
print("⚡ EXTENSION 4: Streaming Agent Output")
print("=" * 60)


class StreamingDisplayHandler(BaseCallbackHandler):
    """Custom callback that prints each token/step as it arrives."""

    def on_llm_new_token(self, token: str, **kwargs):
        print(token, end="", flush=True)

    def on_tool_start(self, serialized, input_str, **kwargs):
        tool_name = serialized.get("name", "unknown")
        print(f"\n\n🔧 Calling tool: {tool_name}")
        print(f"   Input: {str(input_str)[:150]}")

    def on_tool_end(self, output, **kwargs):
        print(f"   Result: {str(output)[:200]}")

    def on_agent_action(self, action, **kwargs):
        print(f"\n💭 Thought → {action.log[:300]}")

    def on_agent_finish(self, finish, **kwargs):
        print(f"\n\n✅ Final Answer: {finish.output}")


streaming_llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0,
    streaming=True,
    callbacks=[StreamingDisplayHandler()],
)

stream_agent = create_react_agent(llm=streaming_llm, tools=tools, prompt=prompt)
stream_executor = AgentExecutor(
    agent=stream_agent,
    tools=tools,
    memory=ConversationBufferMemory(
        memory_key="history", return_messages=False,
        input_key="input", output_key="output"
    ),
    max_iterations=6,
    handle_parsing_errors=True,
    verbose=False,
)

print("🚀 Running agent with live streaming output...\n")
ltm_ctx = ltm.load_memory_variables({"prompt": "streaming test"}).get("ltm_context", "")
stream_executor.invoke({
    "input": "Search for the latest news about LangChain updates and summarise the top 3 items.",
    "ltm_context": ltm_ctx,
})

# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("🎯 LAB SUMMARY")
print("=" * 60)
print("""
┌────────────────────┬────────────────────────────┬────────────────────────────────┐
│ Component          │ Class / Tool               │ Purpose                        │
├────────────────────┼────────────────────────────┼────────────────────────────────┤
│ STM (Buffer)       │ ConversationBufferMemory   │ Full conversation this session │
│ STM (Summary)      │ ConversationSummaryMemory  │ Compressed history, saves $    │
│ LTM (Semantic)     │ VectorStoreRetrieverMemory │ Semantic recall across sessions│
│ LTM (Structured)   │ SQLite + StructuredTool    │ Exact lookup of user facts     │
│ Web Search         │ TavilySearchResults        │ Real-time grounded answers     │
│ Code Execution     │ PythonREPLTool             │ Dynamic computation            │
│ Calculator         │ Custom Tool                │ Safe arithmetic                │
│ Self-Critique      │ Reflexion chain            │ Iterative quality improvement  │
│ Streaming          │ BaseCallbackHandler        │ Live progress display          │
└────────────────────┴────────────────────────────┴────────────────────────────────┘

Key Takeaways:
  1. STM ≠ LTM — they serve different purposes and should be used together
  2. Buffer vs Summary — choose based on session length and token budget
  3. LTM requires a retrieval strategy — semantic (Chroma) or structured (SQL)
  4. Reflexion improves quality — at the cost of latency and tokens
  5. Streaming is a UX necessity — always add it before going to production
""")

print("✅ Pipeline complete!")