# -*- coding: utf-8 -*-
"""Multipart_upload.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_3jebnSIlKRI5lOCRcakUrSGC-IolZz
"""

import pytesseract
from PIL import Image
from pdf2image import convert_from_path
import PyPDF2

pdf_file_path = '/content/task_multipart.pdf'
ocr_extracted_text = []

print('Starting OCR with pdf2image and Tesseract...')

# Convert PDF to a list of images, specifying the poppler path
# In Google Colab, poppler utilities are usually in /usr/bin/
images = convert_from_path(pdf_file_path, poppler_path='/usr/bin/')

for i, image in enumerate(images):
    print(f'Processing page {i + 1}/{len(images)}...')
    # Use Tesseract to do OCR on the image
    text = pytesseract.image_to_string(image)
    ocr_extracted_text.append(text)
    print(f'--- Page {i + 1} (OCR) ---\n{text[:500]}...\n') # Print first 500 chars of each page

full_ocr_text = '\n'.join(ocr_extracted_text)
print("OCR text extraction complete. The full text is available in 'full_ocr_text'.")

import random
import time

class Agent:
    """A simulated agent that does N steps of work. Pure simulation - no LLM, no network."""

    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step # set to an int to force a deterministic failure

    def run(self, listener):
        for step in range(1, self.steps + 1):
            time.sleep(random.uniform(0.05, 0.2)) # simulate work / latency

            if self.fail_at_step and step == self.fail_at_step:
                raise RuntimeError(f"{self.name} failed at step {step}")

            listener(self.name, step, self.steps)

class Orchestrator:
    def __init__(self, agents, listener):
        self.agents = agents
        self.listener = listener

    def run(self):
        for agent in self.agents:
            agent.run(self.listener)

def progress_listener(agent_name, step, total_steps):
    # The "before" state: an unstructured print, just like the AWS sample's byte counter.
    print(f"{agent_name}: step {step}/{total_steps}")

def main():
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4),
        Agent("Reviewer", 2)
    ]

    # To exercise the failure path, set e.g.
    # agents = [
    #     Agent("Planner", 3),
    #     Agent("Researcher", 6),
    #     Agent("Writer", 4, fail_at_step=2),
    #     Agent("Reviewer", 2)
    # ]

    orchestrator = Orchestrator(agents, progress_listener)
    orchestrator.run()

    print("Done")

if __name__ == "__main__":
    main()

"""#Correlate everystep"""

import random
import time
import uuid
from dataclasses import dataclass
from datetime import datetime

@dataclass
class Event:
    timestamp: datetime
    event_type: str
    agent_name: str
    trace_id: str
    span_id: str
    duration: float = 0.0
    status: str = ""
    message: str = ""


class Agent:
    """A simulated agent that does N steps of work. Pure simulation - no LLM, no network."""

    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step # set to an int to force a deterministic failure

    def run(self, listener, trace_id, span_id):
        start_time = time.time()
        listener(Event(datetime.now(), "agent_start", self.name, trace_id, span_id, message="Starting agent run."))

        try:
            for step in range(1, self.steps + 1):
                step_start_time = time.time()
                time.sleep(random.uniform(0.05, 0.2)) # simulate work / latency

                if self.fail_at_step and step == self.fail_at_step:
                    raise RuntimeError(f"{self.name} failed at step {step}")

                step_duration = time.time() - step_start_time
                listener(Event(datetime.now(), "agent_progress", self.name, trace_id, span_id,
                               duration=step_duration, status=f"step {step}/{self.steps}",
                               message=f"{self.name}: step {step}/{self.steps}"))

            duration = time.time() - start_time
            listener(Event(datetime.now(), "agent_end", self.name, trace_id, span_id, duration=duration, status="success", message="Agent run completed."))
        except Exception as e:
            duration = time.time() - start_time
            listener(Event(datetime.now(), "agent_error", self.name, trace_id, span_id, duration=duration, status="error", message=f"Agent run failed: {e}"))
            raise # Re-raise the exception to propagate failure


class Orchestrator:
    def __init__(self, agents, listener):
        self.agents = agents
        self.listener = listener

    def run(self):
        trace_id = str(uuid.uuid4()) # Generate a unique trace_id for this run
        self.listener(Event(datetime.now(), "orchestrator_start", "Orchestrator", trace_id, str(uuid.uuid4()), message=f"Orchestrator starting with trace_id: {trace_id}"))

        for agent in self.agents:
            span_id = str(uuid.uuid4()) # Generate a unique span_id for each agent's execution
            try:
                agent.run(self.listener, trace_id, span_id)
            except RuntimeError as e:
                self.listener(Event(datetime.now(), "orchestrator_error", "Orchestrator", trace_id, span_id, status="error", message=f"Orchestrator caught agent error: {e}"))
                print(f"Orchestrator stopping due to agent failure: {e}")
                break # Stop orchestration if an agent fails
        else:
            self.listener(Event(datetime.now(), "orchestrator_end", "Orchestrator", trace_id, str(uuid.uuid4()), status="success", message="Orchestrator completed all agents."))

        print("Done")

def progress_listener(event: Event):
    # The "before" state: an unstructured print, just like the AWS sample's byte counter.
    # Now using structured Event object
    if event.event_type == "agent_progress":
        print(f"{event.agent_name}: step {event.status.split('/')[-2].strip()}/{event.status.split('/')[-1].strip()} (Trace: {event.trace_id[:8]}..., Span: {event.span_id[:8]}...)")
    else:
        print(f"[{event.timestamp.strftime('%H:%M:%S')}] {event.event_type.upper()}: Agent='{event.agent_name}', Status='{event.status}', Trace='{event.trace_id[:8]}...', Span='{event.span_id[:8]}...', Message='{event.message}'")

def main():
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4),
        Agent("Reviewer", 2)
    ]

    # To exercise the failure path, set e.g.
    # agents = [
    #     Agent("Planner", 3),
    #     Agent("Researcher", 6),
    #     Agent("Writer", 4, fail_at_step=2),
    #     Agent("Reviewer", 2)
    # ]

    orchestrator = Orchestrator(agents, progress_listener)
    orchestrator.run()

if __name__ == "__main__":
    main()

"""Progress and pace"""

import random
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta
import math # Import math for ceil

@dataclass
class Event:
    timestamp: datetime = field(default_factory=datetime.now)
    event_type: str = ""
    agent_name: str = ""
    trace_id: str = ""
    span_id: str = ""
    duration: float = 0.0
    status: str = ""
    message: str = ""
    step: int = 0 # Added for easier tracking of current step
    total_steps: int = 0 # Added for easier tracking of total steps


class Agent:
    """A simulated agent that does N steps of work. Pure simulation - no LLM, no network."""

    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step # set to an int to force a deterministic failure

    def run(self, listener, trace_id, span_id):
        start_time = time.time()
        listener(Event(event_type="agent_start", agent_name=self.name, trace_id=trace_id, span_id=span_id, message="Starting agent run."))

        try:
            for step in range(1, self.steps + 1):
                step_start_time = time.time()
                time.sleep(random.uniform(0.05, 0.2)) # simulate work / latency

                if self.fail_at_step and step == self.fail_at_step:
                    raise RuntimeError(f"{self.name} failed at step {step}")

                step_duration = time.time() - step_start_time
                listener(Event(event_type="agent_progress", agent_name=self.name, trace_id=trace_id, span_id=span_id,
                               duration=step_duration, status=f"step {step}/{self.steps}",
                               message=f"{self.name}: step {step}/{self.steps}",
                               step=step, total_steps=self.steps))

            duration = time.time() - start_time
            listener(Event(event_type="agent_end", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="success", message="Agent run completed."))
        except Exception as e:
            duration = time.time() - start_time
            listener(Event(event_type="agent_error", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="error", message=f"Agent run failed: {e}"))
            raise # Re-raise the exception to propagate failure


class Orchestrator:
    def __init__(self, agents, listener):
        self.agents = agents
        self.listener = listener

    def run(self):
        trace_id = str(uuid.uuid4()) # Generate a unique trace_id for this run
        orchestrator_span_id = str(uuid.uuid4())
        self.listener(Event(event_type="orchestrator_start", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id, message=f"Orchestrator starting with trace_id: {trace_id}"))
        run_start_time = time.time()
        total_agent_steps = sum(agent.steps for agent in self.agents)
        current_global_step = 0

        for agent in self.agents:
            span_id = str(uuid.uuid4()) # Generate a unique span_id for each agent's execution
            try:
                agent.run(self.listener, trace_id, span_id)
            except RuntimeError as e:
                self.listener(Event(event_type="orchestrator_error", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id, status="error", message=f"Orchestrator caught agent error: {e}"))
                print(f"Orchestrator stopping due to agent failure: {e}")
                break # Stop orchestration if an agent fails
        else:
            duration = time.time() - run_start_time
            self.listener(Event(event_type="orchestrator_end", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id, duration=duration, status="success", message="Orchestrator completed all agents."))

        print("Done")

class EventCollector:
    def __init__(self):
        self.events = []
        self.run_start_time = None
        self.total_pipeline_steps = 0
        self.agent_spans = {}

    def collect(self, event: Event):
        self.events.append(event)
        if event.event_type == "orchestrator_start":
            self.run_start_time = event.timestamp
            # Calculate total pipeline steps based on the agents in the orchestrator
            # This assumes the orchestrator is initialized with the full list of agents
            # For a more robust solution, Orchestrator could emit this total.
            # For now, we'll infer it from the first agent_progress events or Orchestrator initialization.

        if event.event_type == "agent_progress" and event.trace_id not in self.agent_spans:
             # This is a temporary way to get total_pipeline_steps if not set by orchestrator
            # A better way would be for Orchestrator to emit this in its start event
            all_agents_steps = {e.agent_name: e.total_steps for e in self.events if e.event_type == "agent_progress"}
            self.total_pipeline_steps = sum(all_agents_steps.values())

        if event.event_type == "agent_start":
            self.agent_spans[event.span_id] = {"agent_name": event.agent_name, "start_time": event.timestamp, "end_time": None, "steps_finished": 0, "total_steps": 0}
        elif event.event_type == "agent_progress":
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["steps_finished"] = event.step
                self.agent_spans[event.span_id]["total_steps"] = event.total_steps
        elif event.event_type == "agent_end" or event.event_type == "agent_error":
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["end_time"] = event.timestamp
                if event.event_type == "agent_end": # Ensure steps_finished is accurate for successful completion
                     self.agent_spans[event.span_id]["steps_finished"] = event.total_steps


    def calculate_pipeline_progress(self):
        if not self.total_pipeline_steps:
            return 0, 0, 0.0 # percentage, completed steps, total steps

        completed_steps_across_all_agents = 0
        for span_data in self.agent_spans.values():
            completed_steps_across_all_agents += span_data["steps_finished"]

        percent_complete = (completed_steps_across_all_agents / self.total_pipeline_steps) * 100
        return percent_complete, completed_steps_across_all_agents, self.total_pipeline_steps

    def calculate_throughput(self):
        if not self.run_start_time:
            return 0.0

        current_time = datetime.now()
        elapsed_time = (current_time - self.run_start_time).total_seconds()
        if elapsed_time == 0:
            return 0.0

        _, completed_steps, _ = self.calculate_pipeline_progress()
        return completed_steps / elapsed_time

    def get_per_agent_durations(self):
        durations = {}
        for span_id, data in self.agent_spans.items():
            if data["start_time"] and data["end_time"]:
                duration = (data["end_time"] - data["start_time"]).total_seconds()
                durations[data["agent_name"]] = duration
        return durations

def main():
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4),
        Agent("Reviewer", 2)
    ]

    # To exercise the failure path, set e.g.
    # agents = [
    #     Agent("Planner", 3),
    #     Agent("Researcher", 6),
    #     Agent("Writer", 4, fail_at_step=2),
    #     Agent("Reviewer", 2)
    # ]

    event_collector = EventCollector()

    def combined_listener(event: Event):
        event_collector.collect(event)

        # Original progress_listener logic
        if event.event_type == "agent_progress":
            print(f"{event.agent_name}: step {event.step}/{event.total_steps} (Trace: {event.trace_id[:8]}..., Span: {event.span_id[:8]}...)")
        else:
            print(f"[{event.timestamp.strftime('%H:%M:%S')}] {event.event_type.upper()}: Agent='{event.agent_name}', Status='{event.status}', Trace='{event.trace_id[:8]}...', Span='{event.span_id[:8]}...', Message='{event.message}'")

        # Add pipeline-level metrics for progress events
        if event.event_type == "agent_progress":
            percent, completed_steps, total_steps = event_collector.calculate_pipeline_progress()
            throughput = event_collector.calculate_throughput()
            print(f"  -> Pipeline: {percent:.1f}% complete ({completed_steps}/{total_steps} steps), Throughput: {throughput:.2f} steps/sec")

        # Print per-agent durations when the orchestration ends
        if event.event_type == "orchestrator_end" or event.event_type == "orchestrator_error":
            agent_durations = event_collector.get_per_agent_durations()
            print("\n--- Per-Agent Durations ---")
            for agent_name, duration in agent_durations.items():
                print(f"  {agent_name}: {duration:.2f} seconds")
            print("---------------------------")


    orchestrator = Orchestrator(agents, combined_listener)
    orchestrator.run()

if __name__ == "__main__":
    main()

"""Structured_lifecycle_events"""

import random
import time
import uuid
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
import math

@dataclass
class Event:
    timestamp: datetime = field(default_factory=datetime.now)
    event_type: str = "" # Maps to 'event' in JSON output
    agent_name: str = "" # Maps to 'agent' in JSON output
    trace_id: str = ""
    span_id: str = ""
    duration: float = 0.0
    status: str = ""
    message: str = ""
    step: int = 0
    total_steps: int = 0

    def to_json_dict(self):
        # Convert dataclass to dict, handle datetime, and rename fields as requested
        data = asdict(self)
        data['timestamp'] = self.timestamp.isoformat()
        data['event'] = data.pop('event_type')
        data['agent'] = data.pop('agent_name')
        return data

class Agent:
    """A simulated agent that does N steps of work. Pure simulation - no LLM, no network."""

    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step # set to an int to force a deterministic failure

    def run(self, listener, trace_id, span_id):
        start_time = time.time()
        listener(Event(event_type="agent_started", agent_name=self.name, trace_id=trace_id, span_id=span_id, message="Starting agent run.", total_steps=self.steps))

        try:
            # Throttling logic for agent_progress events
            progress_thresholds = [0.25, 0.50, 0.75]
            last_reported_threshold_idx = -1 # Index of the last threshold reported

            for step in range(1, self.steps + 1):
                step_start_time = time.time()
                time.sleep(random.uniform(0.05, 0.2)) # simulate work / latency

                if self.fail_at_step and step == self.fail_at_step:
                    raise RuntimeError(f"{self.name} failed at step {step}")

                current_progress_percentage = step / self.steps
                for i, threshold in enumerate(progress_thresholds):
                    if current_progress_percentage >= threshold and i > last_reported_threshold_idx:
                        step_duration = time.time() - step_start_time
                        listener(Event(event_type="agent_progress", agent_name=self.name, trace_id=trace_id, span_id=span_id,
                                       duration=step_duration, status=f"step {step}/{self.steps}",
                                       message=f"{self.name}: {int(threshold*100)}% complete ({step}/{self.steps})",
                                       step=step, total_steps=self.steps))
                        last_reported_threshold_idx = i
                        break # Only report the highest reached threshold at any point

            duration = time.time() - start_time
            listener(Event(event_type="agent_completed", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="success", message="Agent run completed.", step=self.steps, total_steps=self.steps))
        except Exception as e:
            duration = time.time() - start_time
            listener(Event(event_type="agent_failed", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="error", message=f"Agent run failed: {e}", step=step, total_steps=self.steps))
            raise # Re-raise the exception to propagate failure


class Orchestrator:
    def __init__(self, agents, listener):
        self.agents = agents
        self.listener = listener

    def run(self):
        trace_id = str(uuid.uuid4()) # Generate a unique trace_id for this run
        orchestrator_span_id = str(uuid.uuid4())

        total_possible_steps_across_all_agents = sum(agent.steps for agent in self.agents)
        # Inform the listener/collector about the total steps for the entire pipeline
        self.listener(Event(event_type="orchestrator_start", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id,
                            message=f"Orchestrator starting with trace_id: {trace_id}", total_steps=total_possible_steps_across_all_agents))

        run_start_time = time.time()
        failed_agent_name = None
        final_status = "success"

        for agent in self.agents:
            span_id = str(uuid.uuid4()) # Generate a unique span_id for each agent's execution
            try:
                agent.run(self.listener, trace_id, span_id)
            except RuntimeError as e:
                failed_agent_name = agent.name
                final_status = "failure"
                # The agent_failed event is already emitted by the agent itself.
                # Orchestrator just needs to log its own error and break.
                self.listener(Event(event_type="orchestrator_error", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id, status="error", message=f"Orchestrator caught agent error: {e}"))
                # print(f"Orchestrator stopping due to agent failure: {e}") # Replaced by JSON output
                break # Stop orchestration if an agent fails

        duration = time.time() - run_start_time

        self.listener(Event(event_type="run_summary", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id,
                            duration=duration, status=final_status, message=f"Orchestrator run {final_status}."))


class EventCollector:
    def __init__(self):
        self.events = []
        self.run_start_time = None
        self.total_pipeline_steps = 0
        self.agent_spans = {}
        self.orchestrator_trace_id = None # Store the trace_id for the current run

    def collect(self, event: Event):
        self.events.append(event)
        if event.event_type == "orchestrator_start":
            self.run_start_time = event.timestamp
            self.orchestrator_trace_id = event.trace_id
            self.total_pipeline_steps = event.total_steps # Set total pipeline steps from orchestrator_start
            self.agent_spans = {} # Reset agent_spans for a new run

        if event.event_type == "agent_started": # Renamed from agent_start
            self.agent_spans[event.span_id] = {"agent_name": event.agent_name, "start_time": event.timestamp, "end_time": None, "steps_finished": 0, "total_steps": event.total_steps, "status": "running"}
        elif event.event_type == "agent_progress":
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["steps_finished"] = event.step
                # total_steps for agent is already set in agent_started, not necessarily updated here.
        elif event.event_type == "agent_completed" or event.event_type == "agent_failed": # Renamed from agent_end/agent_error
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["end_time"] = event.timestamp
                self.agent_spans[event.span_id]["status"] = event.status
                if event.event_type == "agent_completed": # Ensure steps_finished is accurate for successful completion
                     self.agent_spans[event.span_id]["steps_finished"] = event.total_steps


    def calculate_pipeline_progress(self):
        if self.total_pipeline_steps == 0:
            return 0, 0, 0.0 # percentage, completed steps, total steps

        completed_steps_across_all_agents = 0
        for span_data in self.agent_spans.values():
            completed_steps_across_all_agents += span_data["steps_finished"]

        if self.total_pipeline_steps == 0:
            return 0, completed_steps_across_all_agents, self.total_pipeline_steps

        percent_complete = (completed_steps_across_all_agents / self.total_pipeline_steps) * 100
        return percent_complete, completed_steps_across_all_agents, self.total_pipeline_steps

    def calculate_throughput(self):
        if not self.run_start_time:
            return 0.0

        current_time = datetime.now()
        elapsed_time = (current_time - self.run_start_time).total_seconds()
        if elapsed_time <= 0:
            return 0.0

        _, completed_steps, _ = self.calculate_pipeline_progress()
        return completed_steps / elapsed_time

    def get_per_agent_durations(self):
        durations = {}
        for span_id, data in self.agent_spans.items():
            if data["start_time"] and data["end_time"]:
                duration = (data["end_time"] - data["start_time"]).total_seconds()
                durations[data["agent_name"]] = duration
        return durations

    def get_failed_agent_info(self):
        for span_data in self.agent_spans.values():
            if span_data.get("status") == "error":
                return span_data["agent_name"], span_data.get("steps_finished", 0)
        return None, None


def main():
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4),
        Agent("Reviewer", 2)
    ]

    # To exercise the failure path, set e.g.
    # agents = [
    #     Agent("Planner", 3),
    #     Agent("Researcher", 6),
    #     Agent("Writer", 4, fail_at_step=2),
    #     Agent("Reviewer", 2)
    # ]

    event_collector = EventCollector()

    def combined_listener(event: Event):
        # The EventCollector needs to process events regardless of throttling.
        event_collector.collect(event)

        # Prepare base dictionary for JSON output
        output_dict = event.to_json_dict()

        if event.event_type == "agent_progress":
            # Add progress/pace fields to agent_progress events
            percent, completed_steps, total_pipeline_steps = event_collector.calculate_pipeline_progress()
            throughput = event_collector.calculate_throughput()
            output_dict.update({
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2)
            })
            print(json.dumps(output_dict))
        elif event.event_type == "run_summary":
            # Populate summary details from event_collector
            percent, completed_steps, total_pipeline_steps = event_collector.calculate_pipeline_progress()
            throughput = event_collector.calculate_throughput()
            agent_durations = event_collector.get_per_agent_durations()
            failed_agent_name, failed_step = event_collector.get_failed_agent_info()

            output_dict.update({
                "final_status": event.status,
                "total_duration_sec": round(event.duration, 2),
                "agents_completed": [data["agent_name"] for data in event_collector.agent_spans.values() if data.get("status") == "success"],
                "failed_agent": failed_agent_name,
                "failed_step_on_agent": failed_step,
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2),
                "per_agent_durations": {name: round(d, 2) for name, d in agent_durations.items()}
            })
            print(json.dumps(output_dict, indent=2)) # Pretty print summary
        else:
            # For other events (started, completed, failed, orchestrator_start/error)
            print(json.dumps(output_dict))


    orchestrator = Orchestrator(agents, combined_listener)
    orchestrator.run()

if __name__ == "__main__":
    main()

"""Failure_Localization"""

import random
import time
import uuid
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
import math

@dataclass
class Event:
    timestamp: datetime = field(default_factory=datetime.now)
    event_type: str = "" # Maps to 'event' in JSON output
    agent_name: str = "" # Maps to 'agent' in JSON output
    trace_id: str = ""
    span_id: str = ""
    duration: float = 0.0
    status: str = ""
    message: str = ""
    step: int = 0
    total_steps: int = 0

    def to_json_dict(self):
        # Convert dataclass to dict, handle datetime, and rename fields as requested
        data = asdict(self)
        data['timestamp'] = self.timestamp.isoformat()
        data['event'] = data.pop('event_type')
        data['agent'] = data.pop('agent_name')
        return data

class Agent:
    """A simulated agent that does N steps of work. Pure simulation - no LLM, no network."""

    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step # set to an int to force a deterministic failure

    def run(self, listener, trace_id, span_id):
        agent_run_start_time = time.time() # Overall start time for the agent run
        listener(Event(event_type="agent_started", agent_name=self.name, trace_id=trace_id, span_id=span_id, message="Starting agent run.", total_steps=self.steps))

        try:
            # Throttling logic for agent_progress events
            progress_thresholds = [0.25, 0.50, 0.75]
            last_reported_threshold_idx = -1 # Index of the last threshold reported

            for step in range(1, self.steps + 1):
                step_start_time_current = time.time() # Start time for the current step
                time.sleep(random.uniform(0.05, 0.2)) # simulate work / latency
                step_duration_current = time.time() - step_start_time_current # Duration for the current step

                if self.fail_at_step and step == self.fail_at_step:
                    raise RuntimeError(f"{self.name} failed at step {step}")

                current_progress_percentage = step / self.steps
                for i, threshold in enumerate(progress_thresholds):
                    # Check if we crossed a new threshold and it's not the final step (100% is agent_completed)
                    if current_progress_percentage >= threshold and i > last_reported_threshold_idx and step < self.steps:
                        listener(Event(event_type="agent_progress", agent_name=self.name, trace_id=trace_id, span_id=span_id,
                                       duration=step_duration_current, status=f"step {step}/{self.steps}",
                                       message=f"{self.name}: {int(threshold*100)}% complete ({step}/{self.steps})",
                                       step=step, total_steps=self.steps))
                        last_reported_threshold_idx = i
                        break # Only report the highest reached threshold at any point

            duration = time.time() - agent_run_start_time # Overall agent duration
            listener(Event(event_type="agent_completed", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="success", message="Agent run completed.", step=self.steps, total_steps=self.steps))
        except Exception as e:
            duration = time.time() - agent_run_start_time
            listener(Event(event_type="agent_failed", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="error", message=f"Agent run failed: {e}", step=step, total_steps=self.steps))
            raise # Re-raise the exception to propagate failure


class Orchestrator:
    def __init__(self, agents, listener):
        self.agents = agents
        self.listener = listener

    def run(self):
        trace_id = str(uuid.uuid4()) # Generate a unique trace_id for this run
        orchestrator_span_id = str(uuid.uuid4())

        total_possible_steps_across_all_agents = sum(agent.steps for agent in self.agents)
        # Inform the listener/collector about the total steps for the entire pipeline
        self.listener(Event(event_type="orchestrator_start", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id,
                            message=f"Orchestrator starting with trace_id: {trace_id}", total_steps=total_possible_steps_across_all_agents))

        run_start_time = time.time()
        failed_agent_name = None
        final_status = "success"

        for agent in self.agents:
            span_id = str(uuid.uuid4()) # Generate a unique span_id for each agent's execution
            try:
                agent.run(self.listener, trace_id, span_id)
            except RuntimeError as e:
                failed_agent_name = agent.name
                final_status = "failure"
                # The agent_failed event is already emitted by the agent itself.
                # Orchestrator just needs to log its own error and break.
                self.listener(Event(event_type="orchestrator_error", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id, status="error", message=f"Orchestrator caught agent error: {e}"))
                break # Stop orchestration if an agent fails

        duration = time.time() - run_start_time

        self.listener(Event(event_type="run_summary", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id,
                            duration=duration, status=final_status, message=f"Orchestrator run {final_status}."))


class EventCollector:
    def __init__(self):
        self.events = []
        self.run_start_time = None
        self.total_pipeline_steps = 0
        self.agent_spans = {}
        self.orchestrator_trace_id = None # Store the trace_id for the current run

    def collect(self, event: Event):
        self.events.append(event)
        if event.event_type == "orchestrator_start":
            self.run_start_time = event.timestamp
            self.orchestrator_trace_id = event.trace_id
            self.total_pipeline_steps = event.total_steps # Set total pipeline steps from orchestrator_start
            self.agent_spans = {} # Reset agent_spans for a new run

        if event.event_type == "agent_started": # Renamed from agent_start
            self.agent_spans[event.span_id] = {"agent_name": event.agent_name, "start_time": event.timestamp, "end_time": None, "steps_finished": 0, "total_steps": event.total_steps, "status": "running"}
        elif event.event_type == "agent_progress":
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["steps_finished"] = event.step
                # total_steps for agent is already set in agent_started, not necessarily updated here.
        elif event.event_type == "agent_completed" or event.event_type == "agent_failed": # Renamed from agent_end/agent_error
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["end_time"] = event.timestamp
                self.agent_spans[event.span_id]["status"] = event.status
                if event.event_type == "agent_completed": # Ensure steps_finished is accurate for successful completion
                     self.agent_spans[event.span_id]["steps_finished"] = event.total_steps


    def calculate_pipeline_progress(self):
        if self.total_pipeline_steps == 0:
            return 0, 0, 0.0 # percentage, completed steps, total steps

        completed_steps_across_all_agents = 0
        for span_data in self.agent_spans.values():
            completed_steps_across_all_agents += span_data["steps_finished"]

        if self.total_pipeline_steps == 0:
            return 0, completed_steps_across_all_agents, self.total_pipeline_steps

        percent_complete = (completed_steps_across_all_agents / self.total_pipeline_steps) * 100
        return percent_complete, completed_steps_across_all_agents, self.total_pipeline_steps

    def calculate_throughput(self):
        if not self.run_start_time:
            return 0.0

        current_time = datetime.now()
        elapsed_time = (current_time - self.run_start_time).total_seconds()
        if elapsed_time <= 0:
            return 0.0

        _, completed_steps, _ = self.calculate_pipeline_progress()
        return completed_steps / elapsed_time

    def get_per_agent_durations(self):
        durations = {}
        for span_id, data in self.agent_spans.items():
            if data["start_time"] and data["end_time"]:
                duration = (data["end_time"] - data["start_time"]).total_seconds()
                durations[data["agent_name"]] = duration
        return durations

    def get_failed_agent_info(self):
        # Iterate over items to get both span_id (key) and span_data (value)
        for span_id, span_data in self.agent_spans.items():
            if span_data.get("status") == "error":
                # Find the agent_failed event for this span_id to get message and step
                failed_event = next((e for e in self.events if e.span_id == span_id and e.event_type == 'agent_failed'), None)
                if failed_event:
                     return span_data["agent_name"], failed_event.step, failed_event.message
                return span_data["agent_name"], None, None
        return None, None, None


def main():
    # Agents for a successful run (default)
    # agents = [
    #     Agent("Planner", 3),
    #     Agent("Researcher", 6),
    #     Agent("Writer", 4),
    #     Agent("Reviewer", 2)
    # ]

    # To exercise the failure path, uncomment the following and set fail_at_step
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4, fail_at_step=2), # Writer agent will fail at step 2
        Agent("Reviewer", 2)
    ]

    print("\n--- Running orchestration with a simulated failure (Writer will fail at step 2) ---\n")

    event_collector = EventCollector()

    def combined_listener(event: Event):
        # The EventCollector needs to process events regardless of throttling.
        event_collector.collect(event)

        # Prepare base dictionary for JSON output
        output_dict = event.to_json_dict()

        if event.event_type == "agent_progress":
            # Add progress/pace fields to agent_progress events
            percent, completed_steps, total_pipeline_steps = event_collector.calculate_pipeline_progress()
            throughput = event_collector.calculate_throughput()
            output_dict.update({
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2)
            })
            print(json.dumps(output_dict))
        elif event.event_type == "run_summary":
            # Populate summary details from event_collector
            percent, completed_steps, total_pipeline_steps = event_collector.calculate_pipeline_progress()
            throughput = event_collector.calculate_throughput()
            agent_durations = event_collector.get_per_agent_durations()
            failed_agent_name, failed_step, failed_message = event_collector.get_failed_agent_info()

            output_dict.update({
                "final_status": event.status,
                "total_duration_sec": round(event.duration, 2),
                "agents_completed": [data["agent_name"] for data in event_collector.agent_spans.values() if data.get("status") == "success"],
                "failed_agent": failed_agent_name,
                "failed_step_on_agent": failed_step,
                "failed_message": failed_message,
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2),
                "per_agent_durations": {name: round(d, 2) for name, d in agent_durations.items()}
            })
            print(json.dumps(output_dict, indent=2)) # Pretty print summary
        else:
            # For other events (started, completed, failed, orchestrator_start/error)
            print(json.dumps(output_dict))


    orchestrator = Orchestrator(agents, combined_listener)
    orchestrator.run()

if __name__ == "__main__":
    main()

import json
from collections import defaultdict
from datetime import datetime
import os

# Assume Event, Agent, Orchestrator, EventCollector classes are already defined
# and executable from a previous cell and are accessible in the global scope.
# This code will re-define the main execution logic and the listener to add persistence.

TRACE_FILE = "trace.jsonl"

def setup_file_listener(event_collector_instance):
    """
    Returns a combined listener that collects events, prints them to stdout,
    and appends them to a trace file. This listener wraps the functionality
    that was previously in the main() function's combined_listener.
    """
    # Clear the trace file at the start of a new orchestration run
    # This ensures each run generates its own trace, rather than appending indefinitely.
    if os.path.exists(TRACE_FILE):
        os.remove(TRACE_FILE)
        print(f"Cleared existing trace file: {TRACE_FILE}")

    def combined_listener_with_persistence(event: Event):
        # 1. Collect event in EventCollector
        event_collector_instance.collect(event)

        # Prepare base dictionary for JSON output
        output_dict = event.to_json_dict()

        # 2. Append event to trace.jsonl file
        with open(TRACE_FILE, 'a') as f:
            f.write(json.dumps(output_dict) + '\n')

        # 3. Print to stdout (logic adapted from previous combined_listener)
        if event.event_type == "agent_progress":
            percent, completed_steps, total_pipeline_steps = event_collector_instance.calculate_pipeline_progress()
            throughput = event_collector_instance.calculate_throughput()
            output_dict.update({
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2)
            })
            print(json.dumps(output_dict))
        elif event.event_type == "run_summary":
            percent, completed_steps, total_pipeline_steps = event_collector_instance.calculate_pipeline_progress()
            throughput = event_collector_instance.calculate_throughput()
            agent_durations = event_collector_instance.get_per_agent_durations()
            # EventCollector.get_failed_agent_info is robust, so use it.
            failed_agent_name, failed_step, failed_message = event_collector_instance.get_failed_agent_info()

            output_dict.update({
                "final_status": event.status,
                "total_duration_sec": round(event.duration, 2),
                "agents_completed": [data["agent_name"] for data in event_collector_instance.agent_spans.values() if data.get("status") == "success"],
                "failed_agent": failed_agent_name,
                "failed_step_on_agent": failed_step,
                "failed_message": failed_message,
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2),
                "per_agent_durations": {name: round(d, 2) for name, d in agent_durations.items()}
            })
            print(json.dumps(output_dict, indent=2)) # Pretty print summary
        else:
            print(json.dumps(output_dict))

    return combined_listener_with_persistence


def read_trace_file(filepath):
    """
    Reads a .jsonl file, parses each line as a JSON object,
    and converts the timestamp string back to a datetime object.
    """
    events_data = []
    if not os.path.exists(filepath):
        print(f"Warning: Trace file '{filepath}' not found.")
        return events_data

    with open(filepath, 'r') as f:
        for line in f:
            try:
                event_dict = json.loads(line.strip())
                # Convert timestamp string back to datetime object for sorting
                if 'timestamp' in event_dict:
                    event_dict['timestamp'] = datetime.fromisoformat(event_dict['timestamp'])
                events_data.append(event_dict)
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON from line: {line.strip()} - {e}")
            except ValueError as e:
                print(f"Error parsing timestamp from line: {line.strip()} - {e}")
    return events_data

def print_per_agent_timeline(events_data):
    """
    Prints a timeline of events, grouped by agent.
    """
    print("\n--- Per-Agent Timeline from trace.jsonl ---")

    # Group events by agent_name (which is 'agent' in the JSON output)
    agent_events = defaultdict(list)
    orchestrator_events = []

    for event in events_data:
        if 'agent' in event:
            if event['agent'] == 'Orchestrator':
                orchestrator_events.append(event)
            else:
                agent_events[event['agent']].append(event)

    # Print Orchestrator events first (or wherever desired in the timeline)
    print("\nOrchestrator Events:")
    sorted_orchestrator_events = sorted(orchestrator_events, key=lambda x: x['timestamp'])
    for event in sorted_orchestrator_events:
        time_str = event['timestamp'].strftime('%H:%M:%S.%f')[:-3]
        event_type = event.get('event', 'UNKNOWN_EVENT').ljust(15)
        message = event.get('message', '')
        status = event.get('status', '')
        print(f"  {time_str} - {event_type} - {message} {status}".strip())

    # Sort agent names for consistent output
    sorted_agent_names = sorted(agent_events.keys())

    for agent_name in sorted_agent_names:
        print(f"\nAgent: {agent_name}")
        # Sort events for each agent by timestamp
        sorted_events = sorted(agent_events[agent_name], key=lambda x: x['timestamp'])

        for event in sorted_events:
            time_str = event['timestamp'].strftime('%H:%M:%S.%f')[:-3] # Milliseconds precision
            event_type = event.get('event', 'UNKNOWN_EVENT').ljust(15)
            message = event.get('message', '')
            status = event.get('status', '')
            step_info = f" (Step: {event.get('step')}/{event.get('total_steps')})" if event.get('step') and event.get('total_steps') else ""

            # Special handling for agent_progress to avoid redundant messages
            if event['event'] == 'agent_progress':
                # Message is already formatted like "Planner: 25% complete (1/3)"
                print(f"  {time_str} - {event_type} - {message}")
            elif event['event'] == 'agent_failed':
                print(f"  {time_str} - {event_type} - {status.upper()}: {message}")
            else:
                print(f"  {time_str} - {event_type} - {message} {status}{step_info}".strip())
    print("--- End of Per-Agent Timeline ---")


def main_persisted_trace():
    # Agents for a simulated failure (Writer will fail at step 2)
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4, fail_at_step=2),
        Agent("Reviewer", 2)
    ]

    print("\n--- Running orchestration with file persistence and timeline generation ---")

    event_collector = EventCollector()
    # Pass the event_collector instance to setup_file_listener so it can be used within the closure
    file_listener = setup_file_listener(event_collector)

    orchestrator = Orchestrator(agents, file_listener)
    orchestrator.run()

    print("\nOrchestration finished. Reading trace from file and printing timeline...")

    # Read events back from the trace file
    events_from_file = read_trace_file(TRACE_FILE)

    # Print the per-agent timeline
    print_per_agent_timeline(events_from_file)
    print("\nNote: The full JSON output of events during the run is also printed above,")
    print(f"and a consolidated trace for this run is available in '{TRACE_FILE}'.")

# Execute the new main function
if __name__ == "__main__":
    main_persisted_trace()

import random
import time
import uuid
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
import math
from collections import defaultdict
import os

@dataclass
class Event:
    timestamp: datetime = field(default_factory=datetime.now)
    event_type: str = "" # Maps to 'event' in JSON output
    agent_name: str = "" # Maps to 'agent' in JSON output
    trace_id: str = ""
    span_id: str = ""
    duration: float = 0.0
    status: str = ""
    message: str = ""
    step: int = 0
    total_steps: int = 0

    def to_json_dict(self):
        # Convert dataclass to dict, handle datetime, and rename fields as requested
        data = asdict(self)
        data['timestamp'] = self.timestamp.isoformat()
        data['event'] = data.pop('event_type')
        data['agent'] = data.pop('agent_name')
        return data

class Agent:
    """A simulated agent that does N steps of work. Pure simulation - no LLM, no network."""

    def __init__(self, name, steps, fail_at_step=None, stall_threshold_sec=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step # set to an int to force a deterministic failure
        self.stall_threshold_sec = stall_threshold_sec if stall_threshold_sec is not None else 0.3 # Default stall threshold

    def run(self, listener, trace_id, span_id):
        agent_run_start_time = time.time() # Overall start time for the agent run
        listener(Event(event_type="agent_started", agent_name=self.name, trace_id=trace_id, span_id=span_id, message="Starting agent run.", total_steps=self.steps))

        try:
            # Throttling logic for agent_progress events
            progress_thresholds = [0.25, 0.50, 0.75]
            last_reported_threshold_idx = -1 # Index of the last threshold reported

            for step in range(1, self.steps + 1):
                step_start_time_current = time.time() # Start time for the current step
                time.sleep(random.uniform(0.05, 0.2)) # simulate work / latency
                step_duration_current = time.time() - step_start_time_current # Duration for the current step

                # --- Stall Detection Logic ---
                if self.stall_threshold_sec and step_duration_current > self.stall_threshold_sec:
                    listener(Event(event_type="agent_stalled", agent_name=self.name, trace_id=trace_id, span_id=span_id,
                                   duration=step_duration_current, status=f"step {step}/{self.steps}",
                                   message=f"{self.name} stalled: step {step}/{self.steps} took {step_duration_current:.2f}s (threshold: {self.stall_threshold_sec:.2f}s)",
                                   step=step, total_steps=self.steps))
                # --- End Stall Detection Logic ---

                if self.fail_at_step and step == self.fail_at_step:
                    raise RuntimeError(f"{self.name} failed at step {step}")

                current_progress_percentage = step / self.steps
                for i, threshold in enumerate(progress_thresholds):
                    # Check if we crossed a new threshold and it's not the final step (100% is agent_completed)
                    if current_progress_percentage >= threshold and i > last_reported_threshold_idx and step < self.steps:
                        listener(Event(event_type="agent_progress", agent_name=self.name, trace_id=trace_id, span_id=span_id,
                                       duration=step_duration_current, status=f"step {step}/{self.steps}",
                                       message=f"{self.name}: {int(threshold*100)}% complete ({step}/{self.steps})",
                                       step=step, total_steps=self.steps))
                        last_reported_threshold_idx = i
                        break # Only report the highest reached threshold at any point

            duration = time.time() - agent_run_start_time # Overall agent duration
            listener(Event(event_type="agent_completed", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="success", message="Agent run completed.", step=self.steps, total_steps=self.steps))
        except Exception as e:
            duration = time.time() - agent_run_start_time
            listener(Event(event_type="agent_failed", agent_name=self.name, trace_id=trace_id, span_id=span_id, duration=duration, status="error", message=f"Agent run failed: {e}", step=step, total_steps=self.steps))
            raise # Re-raise the exception to propagate failure


class Orchestrator:
    def __init__(self, agents, listener):
        self.agents = agents
        self.listener = listener

    def run(self):
        trace_id = str(uuid.uuid4()) # Generate a unique trace_id for this run
        orchestrator_span_id = str(uuid.uuid4())

        total_possible_steps_across_all_agents = sum(agent.steps for agent in self.agents)
        # Inform the listener/collector about the total steps for the entire pipeline
        self.listener(Event(event_type="orchestrator_start", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id,
                            message=f"Orchestrator starting with trace_id: {trace_id}", total_steps=total_possible_steps_across_all_agents))

        run_start_time = time.time()
        failed_agent_name = None
        final_status = "success"

        for agent in self.agents:
            span_id = str(uuid.uuid4()) # Generate a unique span_id for each agent's execution
            try:
                agent.run(self.listener, trace_id, span_id)
            except RuntimeError as e:
                failed_agent_name = agent.name
                final_status = "failure"
                # The agent_failed event is already emitted by the agent itself.
                # Orchestrator just needs to log its own error and break.
                self.listener(Event(event_type="orchestrator_error", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id, status="error", message=f"Orchestrator caught agent error: {e}"))
                break # Stop orchestration if an agent fails

        duration = time.time() - run_start_time

        self.listener(Event(event_type="run_summary", agent_name="Orchestrator", trace_id=trace_id, span_id=orchestrator_span_id,
                            duration=duration, status=final_status, message=f"Orchestrator run {final_status}."))


class EventCollector:
    def __init__(self):
        self.events = []
        self.run_start_time = None
        self.total_pipeline_steps = 0
        self.agent_spans = {}
        self.orchestrator_trace_id = None # Store the trace_id for the current run

    def collect(self, event: Event):
        self.events.append(event)
        if event.event_type == "orchestrator_start":
            self.run_start_time = event.timestamp
            self.orchestrator_trace_id = event.trace_id
            self.total_pipeline_steps = event.total_steps # Set total pipeline steps from orchestrator_start
            self.agent_spans = {} # Reset agent_spans for a new run

        if event.event_type == "agent_started": # Renamed from agent_start
            self.agent_spans[event.span_id] = {"agent_name": event.agent_name, "start_time": event.timestamp, "end_time": None, "steps_finished": 0, "total_steps": event.total_steps, "status": "running"}
        elif event.event_type == "agent_progress" or event.event_type == "agent_stalled": # agent_stalled also updates steps_finished
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["steps_finished"] = event.step
                # total_steps for agent is already set in agent_started, not necessarily updated here.
        elif event.event_type == "agent_completed" or event.event_type == "agent_failed": # Renamed from agent_end/agent_error
            if event.span_id in self.agent_spans:
                self.agent_spans[event.span_id]["end_time"] = event.timestamp
                self.agent_spans[event.span_id]["status"] = event.status
                if event.event_type == "agent_completed": # Ensure steps_finished is accurate for successful completion
                     self.agent_spans[event.span_id]["steps_finished"] = event.total_steps


    def calculate_pipeline_progress(self):
        if self.total_pipeline_steps == 0:
            return 0, 0, 0.0 # percentage, completed steps, total steps

        completed_steps_across_all_agents = 0
        for span_data in self.agent_spans.values():
            completed_steps_across_all_agents += span_data["steps_finished"]

        if self.total_pipeline_steps == 0:
            return 0, completed_steps_across_all_agents, self.total_pipeline_steps

        percent_complete = (completed_steps_across_all_agents / self.total_pipeline_steps) * 100
        return percent_complete, completed_steps_across_all_agents, self.total_pipeline_steps

    def calculate_throughput(self):
        if not self.run_start_time:
            return 0.0

        current_time = datetime.now()
        elapsed_time = (current_time - self.run_start_time).total_seconds()
        if elapsed_time <= 0:
            return 0.0

        _, completed_steps, _ = self.calculate_pipeline_progress()
        return completed_steps / elapsed_time

    def get_per_agent_durations(self):
        durations = {}
        for span_id, data in self.agent_spans.items():
            if data["start_time"] and data["end_time"]:
                duration = (data["end_time"] - data["start_time"]).total_seconds()
                durations[data["agent_name"]] = duration
        return durations

    def get_failed_agent_info(self):
        # Iterate over items to get both span_id (key) and span_data (value)
        for span_id, span_data in self.agent_spans.items():
            if span_data.get("status") == "error":
                # Find the agent_failed event for this span_id to get message and step
                failed_event = next((e for e in self.events if e.span_id == span_id and e.event_type == 'agent_failed'), None)
                if failed_event:
                     return span_data["agent_name"], failed_event.step, failed_event.message
                return span_data["agent_name"], None, None
        return None, None, None

TRACE_FILE = "trace.jsonl"

def setup_file_listener(event_collector_instance):
    """
    Returns a combined listener that collects events, prints them to stdout,
    and appends them to a trace file. This listener wraps the functionality
    that was previously in the main() function's combined_listener.
    """
    # Clear the trace file at the start of a new orchestration run
    # This ensures each run generates its own trace, rather than appending indefinitely.
    if os.path.exists(TRACE_FILE):
        os.remove(TRACE_FILE)
        print(f"Cleared existing trace file: {TRACE_FILE}")

    def combined_listener_with_persistence(event: Event):
        # 1. Collect event in EventCollector
        event_collector_instance.collect(event)

        # Prepare base dictionary for JSON output
        output_dict = event.to_json_dict()

        # 2. Append event to trace.jsonl file
        with open(TRACE_FILE, 'a') as f:
            f.write(json.dumps(output_dict) + '\n')

        # 3. Print to stdout (logic adapted from previous combined_listener)
        if event.event_type == "agent_progress" or event.event_type == "agent_stalled": # Include stalled events for progress metrics
            percent, completed_steps, total_pipeline_steps = event_collector_instance.calculate_pipeline_progress()
            throughput = event_collector_instance.calculate_throughput()
            output_dict.update({
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2)
            })
            print(json.dumps(output_dict))
        elif event.event_type == "run_summary":
            percent, completed_steps, total_pipeline_steps = event_collector_instance.calculate_pipeline_progress()
            throughput = event_collector_instance.calculate_throughput()
            agent_durations = event_collector_instance.get_per_agent_durations()
            failed_agent_name, failed_step, failed_message = event_collector_instance.get_failed_agent_info()

            output_dict.update({
                "final_status": event.status,
                "total_duration_sec": round(event.duration, 2),
                "agents_completed": [data["agent_name"] for data in event_collector_instance.agent_spans.values() if data.get("status") == "success"],
                "failed_agent": failed_agent_name,
                "failed_step_on_agent": failed_step,
                "failed_message": failed_message,
                "pipeline_percent_complete": round(percent, 1),
                "pipeline_completed_steps": completed_steps,
                "pipeline_total_steps": total_pipeline_steps,
                "pipeline_throughput_steps_per_sec": round(throughput, 2),
                "per_agent_durations": {name: round(d, 2) for name, d in agent_durations.items()}
            })
            print(json.dumps(output_dict, indent=2)) # Pretty print summary
        else:
            print(json.dumps(output_dict))

    return combined_listener_with_persistence


def read_trace_file(filepath):
    """
    Reads a .jsonl file, parses each line as a JSON object,
    and converts the timestamp string back to a datetime object.
    """
    events_data = []
    if not os.path.exists(filepath):
        print(f"Warning: Trace file '{filepath}' not found.")
        return events_data

    with open(filepath, 'r') as f:
        for line in f:
            try:
                event_dict = json.loads(line.strip())
                # Convert timestamp string back to datetime object for sorting
                if 'timestamp' in event_dict:
                    event_dict['timestamp'] = datetime.fromisoformat(event_dict['timestamp'])
                events_data.append(event_dict)
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON from line: {line.strip()} - {e}")
            except ValueError as e:
                print(f"Error parsing timestamp from line: {line.strip()} - {e}")
    return events_data

def print_per_agent_timeline(events_data):
    """
    Prints a timeline of events, grouped by agent.
    """
    print("\n--- Per-Agent Timeline from trace.jsonl ---")

    # Group events by agent_name (which is 'agent' in the JSON output)
    agent_events = defaultdict(list)
    orchestrator_events = []

    for event in events_data:
        if 'agent' in event:
            if event['agent'] == 'Orchestrator':
                orchestrator_events.append(event)
            else:
                agent_events[event['agent']].append(event)

    # Print Orchestrator events first (or wherever desired in the timeline)
    print("\nOrchestrator Events:")
    sorted_orchestrator_events = sorted(orchestrator_events, key=lambda x: x['timestamp'])
    for event in sorted_orchestrator_events:
        time_str = event['timestamp'].strftime('%H:%M:%S.%f')[:-3]
        event_type = event.get('event', 'UNKNOWN_EVENT').ljust(15)
        message = event.get('message', '')
        status = event.get('status', '')
        print(f"  {time_str} - {event_type} - {message} {status}".strip())

    # Sort agent names for consistent output
    sorted_agent_names = sorted(agent_events.keys())

    for agent_name in sorted_agent_names:
        print(f"\nAgent: {agent_name}")
        # Sort events for each agent by timestamp
        sorted_events = sorted(agent_events[agent_name], key=lambda x: x['timestamp'])

        for event in sorted_events:
            time_str = event['timestamp'].strftime('%H:%M:%S.%f')[:-3] # Milliseconds precision
            event_type = event.get('event', 'UNKNOWN_EVENT').ljust(15)
            message = event.get('message', '')
            status = event.get('status', '')
            step_info = f" (Step: {event.get('step')}/{event.get('total_steps')})" if event.get('step') and event.get('total_steps') else ""

            # Special handling for agent_progress to avoid redundant messages
            if event['event'] == 'agent_progress':
                # Message is already formatted like "Planner: 25% complete (1/3)"
                print(f"  {time_str} - {event_type} - {message}")
            elif event['event'] == 'agent_failed':
                print(f"  {time_str} - {event_type} - {status.upper()}: {message}")
            elif event['event'] == 'agent_stalled': # New handler for stalled events
                print(f"  {time_str} - {event_type} - WARNING: {message}")
            else:
                print(f"  {time_str} - {event_type} - {message} {status}{step_info}".strip())
    print("--- End of Per-Agent Timeline ---")


def main_persisted_trace():
    # Agents for a simulated failure (Writer will fail at step 2)
    # Researcher agent will have a lower stall threshold to demonstrate stalling
    agents = [
        Agent("Planner", 3, stall_threshold_sec=0.25), # Should occasionally stall with default sleep
        Agent("Researcher", 6, stall_threshold_sec=0.15), # More likely to stall
        Agent("Writer", 4, fail_at_step=2, stall_threshold_sec=0.25),
        Agent("Reviewer", 2, stall_threshold_sec=0.25)
    ]

    print("\n--- Running orchestration with file persistence, stall detection, and timeline generation ---")

    event_collector = EventCollector()
    # Pass the event_collector instance to setup_file_listener so it can be used within the closure
    file_listener = setup_file_listener(event_collector)

    orchestrator = Orchestrator(agents, file_listener)
    orchestrator.run()

    print("\nOrchestration finished. Reading trace from file and printing timeline...")

    # Read events back from the trace file
    events_from_file = read_trace_file(TRACE_FILE)

    # Print the per-agent timeline
    print_per_agent_timeline(events_from_file)
    print("\nNote: The full JSON output of events during the run is also printed above,")
    print(f"and a consolidated trace for this run is available in '{TRACE_FILE}'.")

# Execute the new main function
if __name__ == "__main__":
    main_persisted_trace()

# Multi-Agent System with Enhanced Observability

This project demonstrates the evolution of an observability layer for a simulated multi-agent system. Starting from a basic execution flow, the system was progressively enhanced to provide rich, structured insights into agent activities, pipeline progress, and failure diagnostics.

## Table of Contents
1.  [Project Overview](#project-overview)
2.  [Initial Setup: PDF Text Extraction](#initial-setup-pdf-text-extraction)
3.  [Core Multi-Agent System (Initial State)](#core-multi-agent-system-initial-state)
4.  [Phase 1: Event Definition & Correlation](#phase-1-event-definition--correlation)
5.  [Phase 2: Event Collection & Pipeline Metrics](#phase-2-event-collection--pipeline-metrics)
6.  [Phase 3: Structured Lifecycle Events & Throttling](#phase-3-structured-lifecycle-events--throttling)
7.  [Phase 4: Failure Localization & Comprehensive Run Summary](#phase-4-failure-localization--comprehensive-run-summary)
8.  [Phase 5: Event Persistence (`trace.jsonl`)](#phase-5-event-persistence-tracejsonl)
9.  [Phase 6: Per-Agent Timeline Visualization](#phase-6-per-agent-timeline-visualization)
10. [Phase 7: Stall Detection](#phase-7-stall-detection)
11. [How to Run](#how-to-run)
12. [Future Enhancements](#future-enhancements)

## Project Overview
This project focuses on building a robust observability layer for a simulated multi-agent system. The core system consists of an `Orchestrator` managing several `Agent` instances, each performing a series of steps. The observability layer provides:
*   **Event Correlation**: Using `trace_id` and `span_id`.
*   **Structured Events**: JSON-formatted events for various lifecycle stages.
*   **Pipeline Metrics**: Progress, throughput, and per-agent durations.
*   **Failure Diagnostics**: Pinpointing failed agents, steps, and error messages.
*   **Event Persistence**: Storing all events in a `trace.jsonl` file.
*   **Timeline Visualization**: Reconstructing and displaying per-agent timelines from persisted data.
*   **Stall Detection**: Identifying agents that take too long to complete a step.

## Initial Setup: PDF Text Extraction
Before delving into the observability features, an initial task involved extracting text from a PDF document (`task_multipart.pdf`). This was done using OCR, specifically `pdf2image` (to convert PDF pages to images) and `pytesseract` (to perform OCR on the images). The extracted text was stored in `full_ocr_text` for potential further analysis.

## Core Multi-Agent System (Initial State)
The initial system comprised simple `Agent` and `Orchestrator` classes. Agents performed a set number of steps, and the orchestrator managed their execution. Logging was basic, printing unstructured messages to stdout.

### Key Components:
*   `Agent`: Simulates work by pausing for a random duration for each step.
*   `Orchestrator`: Manages the sequential execution of agents.
*   `progress_listener`: A simple function to print agent progress.

## Phase 1: Event Definition & Correlation
The first major step in building observability was to define a structured `Event` dataclass and introduce correlation identifiers (`trace_id` and `span_id`).

### Changes:
*   **`Event` Dataclass**: A `dataclass` named `Event` was introduced, including fields like `timestamp`, `event_type`, `agent_name`, `trace_id`, `span_id`, `duration`, `status`, `message`, `step`, and `total_steps`. A `to_json_dict` method was added for structured output.
*   **`trace_id`**: A unique ID generated per orchestration run, allowing all events related to a single run to be grouped.
*   **`span_id`**: A unique ID generated per agent execution within a run, allowing all events from a specific agent's execution to be grouped.
*   **Agent/Orchestrator Modification**: Both `Agent` and `Orchestrator` classes were updated to generate and pass `trace_id` and `span_id` to the `listener` with every event.

## Phase 2: Event Collection & Pipeline Metrics
To make sense of the events and calculate pipeline-level metrics, an `EventCollector` class was introduced.

### Changes:
*   **`EventCollector` Class**: Stores all emitted `Event` objects and maintains the state necessary to calculate metrics.
*   **`calculate_pipeline_progress`**: Computes the overall percentage complete and total completed steps across all agents.
*   **`calculate_throughput`**: Determines the number of steps processed per second for the entire pipeline.
*   **`get_per_agent_durations`**: Calculates the execution time for each individual agent.
*   **Enriched `agent_progress` Events**: `agent_progress` events were updated to include pipeline-level metrics like `pipeline_percent_complete` and `pipeline_throughput_steps_per_sec`.

## Phase 3: Structured Lifecycle Events & Throttling
The event types were refined to be more semantically meaningful, and all output was switched to structured JSON. `agent_progress` events were also throttled to reduce verbosity.

### Changes:
*   **Refined Event Types**: Standardized event types to `agent_started`, `agent_completed`, `agent_failed`, `orchestrator_start`, `orchestrator_error`, and `run_summary`.
*   **JSON Output**: All events printed to stdout are now formatted as JSON strings.
*   **`agent_progress` Throttling**: `agent_progress` events are now emitted only when an agent crosses 25%, 50%, and 75% completion thresholds, preventing excessive logging for very granular steps.

## Phase 4: Failure Localization & Comprehensive Run Summary
Enhanced the system to gracefully handle agent failures and provide a detailed summary at the end of each orchestration run, whether successful or failed.

### Changes:
*   **`agent_failed` Event**: Emitted when an agent encounters an error, capturing the agent's name, the step at which it failed, and the error message.
*   **Orchestrator Graceful Failure Handling**: The `Orchestrator` now catches `RuntimeError` exceptions from agents, logs an `orchestrator_error` event, and stops the pipeline execution.
*   **`run_summary` Event**: A comprehensive event emitted at the very end of an orchestration, detailing:
    *   `final_status` (success/failure)
    *   `total_duration_sec`
    *   List of `agents_completed`
    *   `failed_agent`, `failed_step_on_agent`, and `failed_message` (if applicable)
    *   Overall `pipeline_percent_complete` and `pipeline_throughput_steps_per_sec`.
    *   `per_agent_durations` for all agents that ran.
*   **Bug Fix**: Resolved a `KeyError: 'span_id'` in `EventCollector.get_failed_agent_info` that occurred when trying to retrieve failure details, ensuring accurate reporting.

## Phase 5: Event Persistence (`trace.jsonl`)
To enable post-run analysis and debugging, all events are now persisted to a file.

### Changes:
*   **`trace.jsonl` File**: A file named `trace.jsonl` is created to store every emitted event, with each event written as a separate JSON object on a new line.
*   **`setup_file_listener`**: A wrapper function that modifies the `combined_listener` to also append each event's JSON representation to `trace.jsonl`. This function ensures the file is cleared at the start of each run.
*   **`read_trace_file`**: A utility function to read and parse the `trace.jsonl` file, converting JSON strings back into Python dictionaries (and timestamps back to `datetime` objects).

## Phase 6: Per-Agent Timeline Visualization
Introduced a function to read the persisted `trace.jsonl` file and display events in a structured, per-agent timeline format.

### Changes:
*   **`print_per_agent_timeline`**: This function takes a list of parsed events, groups them by agent (including the Orchestrator), sorts them by timestamp, and prints them in a human-readable timeline format.
*   **Enhanced Readability**: Specific formatting is applied for different event types (e.g., `agent_progress`, `agent_failed`) to highlight key information.

## Phase 7: Stall Detection
Added a mechanism to detect and report when an agent's individual step execution exceeds a predefined time threshold.

### Changes:
*   **`Agent.stall_threshold_sec`**: A new parameter in the `Agent` constructor to set a maximum acceptable duration for a single step. Defaults to `0.3` seconds if not specified.
*   **`agent_stalled` Event**: A new event type emitted by an `Agent` if `step_duration_current` exceeds `stall_threshold_sec`. This event includes details about the step, actual duration, and the threshold.
*   **Timeline Integration**: The `print_per_agent_timeline` function was updated to specifically display `agent_stalled` events with a "WARNING" prefix, making them easily noticeable in the timeline output.
*   **EventCollector Update**: Modified `EventCollector.collect` to include `agent_stalled` events when updating `steps_finished` for pipeline progress metrics.

## How to Run
To run the updated system with all observability features, persistence, and stall detection:

1.  **Ensure all code cells are executed in order.** The `Event`, `Agent`, `Orchestrator`, and `EventCollector` classes are defined across several cells and rely on the latest definitions.
2.  **Locate the `main_persisted_trace()` function.** This function is at the end of the latest code cell defining the observability logic.
3.  **Execute the cell containing `main_persisted_trace()`** (usually the last code cell).

The output will first show the real-time JSON events, and then, after the orchestration completes, it will print the structured per-agent timeline reconstructed from the `trace.jsonl` file.

## Future Enhancements
*   **Hierarchical Spans**: Implement nested `span_id`s to represent sub-tasks within an agent's work, providing a more detailed execution graph.
*   **Interactive UI**: Develop a web-based UI to visualize the trace.jsonl data, allowing for filtering, searching, and graphical representation of timelines and metrics.
*   **External Observability Backend Integration**: Integrate with open-source tools like OpenTelemetry, Prometheus, or commercial APM solutions for advanced monitoring and alerting.
*   **Dynamic Thresholds**: Implement dynamic calculation or machine learning for stall thresholds, adapting to historical performance.
*   **More Complex Agent Interactions**: Simulate agents calling other agents or performing asynchronous tasks to test the robustness of the tracing mechanism in more complex scenarios.