# -*- coding: utf-8 -*-
"""DAY3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBRuV_tUfiS9lmI7jSgeANtDoVcmmjtt

# **MLFLOW**

Complete the MLFlow tracking

a.Logs max_depth and
n_estimators as parameters

b. Logs accuracy and f1 as metrics

c.Logs and register the model under
name"iris-rf-classifier"

d.Sets a tag "team" with value "data science"
"""

!pip install mlflow

import mlflow, mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,f1_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# End any active MLflow run to prevent 'Run is already active' errors
if mlflow.active_run():
    mlflow.end_run()


mlflow.set_tracking_uri("sqlite:///quiz.db")
mlflow.set_experiment("quiz-experiment")

X,y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

MAX_DEPTH= 5
N_ESTIMATORS=100

with mlflow.start_run(run_name="quiz-run"):
  mlflow.log_param("max_depth",MAX_DEPTH)
  mlflow.log_param("n_estimators",N_ESTIMATORS)

  model = RandomForestClassifier(max_depth=MAX_DEPTH,n_estimators=N_ESTIMATORS, random_state=42)
  model.fit(X_train,y_train)
  preds=model.predict(X_test)

  mlflow.log_metric("accuracy",accuracy_score(y_test,preds))
  mlflow.log_metric("f1",f1_score(y_test,preds,average="macro"))

mlflow.sklearn.log_model(model,"random-forest-model",registered_model_name="iris-rf-classifier")
mlflow.set_tag("team","data science")