# -*- coding: utf-8 -*-
"""middleware observability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0SnStFTz-qbno-ZgzSSM99T2LpIjnFc
"""

import structlog, logging, uuid, time, contextvars, asyncio # Added contextvars, asyncio
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.stdlib.LoggerFactory(), # Changed to stdlib.LoggerFactory()
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

# Define a ContextVar to store the correlation ID
correlation_id_ctx = contextvars.ContextVar('correlation_id_ctx', default=None)

# Custom httpx.Auth to propagate the correlation ID
class HttpxCorrelationIdAuth(httpx.Auth):
    def auth_flow(self, request: httpx.Request):
        correlation_id = correlation_id_ctx.get()
        if correlation_id:
            request.headers['X-Correlation-Id'] = correlation_id
        yield request


@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    # Set the correlation ID in the context for the duration of this request
    token = correlation_id_ctx.set(correlation_id)
    start = time.perf_counter()

    try:
        log.info('request.started',
                 path=request.url.path,
                 method=request.method,
                 correlation_id=correlation_id)

        response = await call_next(request)
        elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

        response.headers['X-Correlation-Id'] = correlation_id
        return response
    finally:
        # Reset the context variable to its previous state
        correlation_id_ctx.reset(token)

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

# Mock downstream service to inspect headers
@app.get('/_mock-downstream-service')
async def mock_downstream_service(request: Request):
    log.info('mock_downstream_service.received_request', headers=dict(request.headers))
    return {'message': 'Hello from downstream!', 'received_headers': dict(request.headers)}

# Endpoint to demonstrate correlation ID propagation in outbound calls
@app.get('/call-downstream')
async def call_downstream_service():
    # The correlation ID will be automatically injected by HttpxCorrelationIdAuth
    # as it's active in the current context.
    async with httpx.AsyncClient(auth=HttpxCorrelationIdAuth(), timeout=5.0) as client:
        response = await client.get(f'http://localhost:{SERVER_PORT}/_mock-downstream-service')
        response.raise_for_status()
        downstream_response = response.json()

    # The log message will also include the correlation ID from the context
    log.info('call_downstream.completed', downstream_status=response.status_code)
    return {
        'current_request_correlation_id': correlation_id_ctx.get(),
        'downstream_service_response': downstream_response
    }

print('✅ Logging middleware and routes defined')

# ---
# ## Part 3 — Prometheus Metrics Middleware

# The four golden signals: **Latency, Traffic, Errors, Saturation**. We track all four with Prometheus counters and histograms.


from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST, REGISTRY # Added REGISTRY
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

# Custom business metric: track payment amounts by currency
# Check if metrics are already registered to prevent ValueError on re-run
if 'payment_amount_gbp' not in REGISTRY._names_to_collectors:
    PAYMENT_AMOUNT = Histogram(
        'payment_amount_gbp', 'Payment amount in GBP',
        buckets=[10, 50, 100, 500, 1000, 5000, 10000]
    )
else:
    PAYMENT_AMOUNT = REGISTRY._names_to_collectors['payment_amount_gbp'] # Re-use existing metric

if 'payment_errors_total' not in REGISTRY._names_to_collectors:
    ERROR_COUNT = Counter(
        'payment_errors_total', 'Total payment processing errors',
        ['error_type']
    )
else:
    ERROR_COUNT = REGISTRY._names_to_collectors['payment_errors_total'] # Re-use existing metric

# Auto-instrument all HTTP routes (latency, status codes, method)
# Ensure instrumentation is only applied once
if not hasattr(app, '_instrumented'):
    Instrumentator().instrument(app).expose(app)
    app._instrumented = True

print('✅ Prometheus metrics instrumented')
print('   → /metrics endpoint is now available')
print('   → Tracking: request_count, request_latency, payment_amount')

# ---
# ## Part 4 — Retry Logic with Tenacity

# Payment APIs are flaky under load. We use `tenacity` to retry failed calls with **exponential backoff + jitter** to avoid the thundering herd problem.


import random
import asyncio
from tenacity import (
    retry, stop_after_attempt, wait_exponential,
    retry_if_exception_type, before_sleep_log
)

# Simulate a flaky downstream fraud-check service
call_count = 0

async def flaky_fraud_check(payload: dict) -> dict:
    global call_count
    call_count += 1
    # Fail the first 2 attempts, succeed on 3rd
    if call_count < 3:
        print(f'  ☢️  Attempt {call_count}: fraud API timeout (simulated)')
        raise ConnectionError(f'Fraud API timeout on attempt {call_count}')
    print(f'  ✅ Attempt {call_count}: fraud check passed')
    return {'fraud_score': 0.02, 'decision': 'approved'}


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=0.1, max=2),  # seconds (small for demo)
    retry=retry_if_exception_type((ConnectionError, TimeoutError)),
    reraise=True
)
async def call_fraud_api_with_retry(payload: dict) -> dict:
    return await flaky_fraud_check(payload)


# Test it
print('⇳ Testing retry logic...')
result = asyncio.run(
    call_fraud_api_with_retry({'amount': 1500, 'currency': 'GBP'})
)
print(f'\n📦 Final result: {result}')

# ---
# ## Part 5 — Circuit Breaker with PyBreaker

# If a downstream service is consistently failing, retrying indefinitely makes things **worse**. The circuit breaker trips after `N` failures and returns a fast fallback for 30 seconds — preventing cascade failures.


import pybreaker

class LoggingListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old_state, new_state):
        log.warning('circuit_breaker.state_change',
                    breaker=cb.name,
                    old=str(old_state),
                    new=str(new_state))

# Check if circuit breaker already exists to prevent re-creation on re-run
# This assumes `fraud_breaker` is intended to be a global variable.
if 'fraud_breaker' not in globals():
    fraud_breaker = pybreaker.CircuitBreaker(
        fail_max=3,
        reset_timeout=30,
        listeners=[LoggingListener()],
        name='fraud-api'
    )

def check_fraud_cb(payload: dict) -> dict:
    """Wrapped by circuit breaker — raises CircuitBreakerError when OPEN."""
    # Simulate always-failing service for demo
    raise ConnectionError('Fraud service down')

def safe_fraud_check(payload: dict) -> dict:
    """Call fraud API with circuit breaker; return fallback if circuit is OPEN."""
    try:
        return fraud_breaker.call(check_fraud_cb, payload)
    except pybreaker.CircuitBreakerError:
        print('🔴 Circuit OPEN — returning safe fallback (manual review)')
        return {'fraud_score': None, 'decision': 'manual_review', 'circuit': 'open'}
    except Exception as e:
        return {'fraud_score': None, 'decision': 'error', 'reason': str(e)}

print('📊 Simulating calls to a failing fraud service...')
for i in range(6):
    result = safe_fraud_check({'amount': 200 * (i + 1)})
    print(f'  Call {i+1}: {result} | Circuit state: {fraud_breaker.current_state}')

# ---
# ## Part 6 — Run the Full App

# We start uvicorn in the background and expose it via a public ngrok tunnel so you can hit it from your browser or Postman.


# ⚠️ You need a free ngrok account. Get your token at https://dashboard.ngrok.com
NGROK_TOKEN = 'PASTE_YOUR_TOKEN_HERE'  # ⬅️ replace this

import threading, uvicorn, socket # Added socket
from pyngrok import ngrok, conf
# Used to securely store your API key
from google.colab import userdata

# Retrieve NGROK_TOKEN from Colab secrets
NGROK_TOKEN = userdata.get('NGROK_TOKEN') # Corrected secret name to 'NGROK_TOKEN'

conf.get_default().auth_token = NGROK_TOKEN

# Function to find an available port dynamically
def find_available_port(min_port=8000, max_port=9000):
    for port in range(min_port, max_port + 1):
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.bind(('localhost', port))
                return port
        except OSError:
            continue
    raise IOError('No available ports found')

SERVER_PORT = find_available_port()
print(f"Using dynamic port: {SERVER_PORT}")

def run_server():
    log.info(f"Uvicorn server thread starting on port {SERVER_PORT}...") # Added this line
    config = uvicorn.Config(app, host='0.0.0.0', port=SERVER_PORT, log_level='warning') # Use dynamic port
    server = uvicorn.Server(config)

    try:
        loop = asyncio.get_event_loop()
    except RuntimeError: # No event loop for this thread, create one
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        nest_asyncio.apply(loop) # Apply nest_asyncio to this new loop

    loop.run_until_complete(server.serve())
    log.info("Uvicorn server thread finished serving.") # Added this line

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

import time; time.sleep(5) # Increased sleep duration

# Add a short delay after ngrok.kill() to ensure processes terminate
ngrok.kill()
import time; time.sleep(1) # Added sleep here
tunnel = ngrok.connect(SERVER_PORT) # Use dynamic port
public_url = tunnel.public_url

print(f'🌐 Public URL: {public_url}')
print(f'   Health:   {public_url}/health/ready')
print(f'   Metrics:  {public_url}/metrics')
print(f'   Docs:     {public_url}/docs')

# Quick smoke tests using httpx
import httpx, json

BASE = public_url  # set in the cell above

with httpx.Client() as client:
    # 1 — Health check
    r = client.get(f'{BASE}/health/ready')
    print('Health:', r.json())

    # 2 — POST a payment (watch structured logs above)
    r = client.post(f'{BASE}/payments',
                    json={'amount': 1500, 'currency': 'GBP', 'account': 'ACC-42'},
                    headers={'X-Correlation-Id': 'demo-corr-001'})
    print('Payment:', r.json())
    print('Returned correlation ID:', r.headers.get('X-Correlation-Id'))

    # 3 — Peek at first 500 chars of /metrics
    r = client.get(f'{BASE}/metrics')
    print('\nMetrics (first 500 chars):')
    print(r.text[:500])

# ---
# ## 🔥 Extension Tasks

# ### Extension A — Rate-Limiting Middleware *(Medium)*
# Add a sliding-window rate limiter (e.g., 100 req/min per client IP) using an in-memory dictionary.
# - Return `429 Too Many Requests` with a `Retry-After` header when the limit is exceeded
# - Track limit hits as a Prometheus `Counter`

# ### Extension B — Correlation ID Propagation *(Medium)*
# The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
# - Add a `contextvars.ContextVar` to store the correlation ID per request
# - Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
# - Verify it appears in mock downstream requests

# ### Extension C — Prometheus + Grafana Dashboard *(Advanced)*
# - Export your running `/metrics` to a free [Grafana Cloud](https://grafana.com/products/cloud/) account using the Prometheus remote-write endpoint
# - Build a dashboard with 4 panels: request rate, p99 latency, error rate, circuit breaker trip count

# ### Extension D — Structured Log Aggregation *(Advanced)*
# - Set up a free [Elastic Cloud](https://www.elastic.co/cloud/) cluster or use the Colab local filesystem
# - Configure `structlog` to write logs as newline-delimited JSON to a file
# - Write a query that finds all requests with `latency_ms > 200` for a specific `correlation_id`

"""## Extension A — Rate-Limiting Middleware

This extension adds a sliding-window rate limiter to the FastAPI application. It tracks requests per client IP address and limits the number of requests within a defined time window. If the limit is exceeded, a `429 Too Many Requests` response is returned with a `Retry-After` header.

### Testing the Rate Limiter

Now, let's test the rate limiter by making several rapid requests to an endpoint. You should see `Too many requests` responses after the limit is reached.
"""

import httpx # Ensure httpx is imported if not already
import time # Ensure time is imported

print(f"\nTesting rate limiting (max {RATE_LIMIT_MAX_REQUESTS} requests per {RATE_LIMIT_WINDOW_SECONDS} seconds):")

time.sleep(1) # Add a small delay before starting the rate limit test

# Use a client with a higher timeout
with httpx.Client(timeout=15.0) as client:
    # Make a few requests to trigger the rate limit
    for i in range(RATE_LIMIT_MAX_REQUESTS + 2): # +2 to ensure we hit the limit
        try:
            r = client.get(f'{BASE}/health/live')
            print(f'Request {i+1}: Status {r.status_code}, Response: {r.json()}')
        except httpx.HTTPStatusError as e:
            print(f'Request {i+1}: Status {e.response.status_code}, Error: {e.response.json()}')
        except httpx.ReadTimeout as e:
            print(f'Request {i+1}: ReadTimeout occurred: {e}')
        except Exception as e:
            print(f'Request {i+1}: An unexpected error occurred: {type(e).__name__}: {e}')
        time.sleep(0.5) # Small delay between requests

    # Wait for the rate limit window to reset and try again
    print(f"\nWaiting for {RATE_LIMIT_WINDOW_SECONDS} seconds for rate limit to reset...")
    time.sleep(RATE_LIMIT_WINDOW_SECONDS)

    r = client.get(f'{BASE}/health/live')
    print(f'Request after reset: Status {r.status_code}, Response: {r.json()}')

"""### Extension B — Correlation ID Propagation *(Medium)*
The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
- Add a `contextvars.ContextVar` to store the correlation ID per request
- Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
- Verify it appears in mock downstream requests

### Testing Correlation ID Propagation
"""

# Test correlation ID propagation
print("\nTesting Correlation ID Propagation:")

# Make a request to the /call-downstream endpoint with a custom correlation ID
custom_correlation_id = 'test-correlation-12345'
with httpx.Client(timeout=15.0) as client:
    r = client.get(f'{BASE}/call-downstream',
                   headers={'X-Correlation-Id': custom_correlation_id})
    r.raise_for_status() # Raise an exception for HTTP errors
    response_data = r.json()

    print(f"Response from /call-downstream: {json.dumps(response_data, indent=2)}")

    # Verify that the correlation ID was propagated
    assert response_data['current_request_correlation_id'] == custom_correlation_id
    assert 'x-correlation-id' in response_data['downstream_service_response']['received_headers']
    assert response_data['downstream_service_response']['received_headers']['x-correlation-id'] == custom_correlation_id

    print("✅ Correlation ID propagated successfully!")

# Test with no correlation ID provided (should generate a new one)
print("\nTesting Correlation ID Propagation (no X-Correlation-Id header provided):")
with httpx.Client(timeout=15.0) as client:
    r = client.get(f'{BASE}/call-downstream')
    r.raise_for_status()
    response_data_no_header = r.json()

    print(f"Response from /call-downstream: {json.dumps(response_data_no_header, indent=2)}")

    # Verify that a new correlation ID was generated and propagated
    assert response_data_no_header['current_request_correlation_id'] is not None
    assert 'x-correlation-id' in response_data_no_header['downstream_service_response']['received_headers']
    assert response_data_no_header['downstream_service_response']['received_headers']['x-correlation-id'] == response_data_no_header['current_request_correlation_id']

    print("✅ New Correlation ID generated and propagated successfully!")

"""### Extension C — Prometheus + Grafana Dashboard

We have now configured the FastAPI application to periodically push its Prometheus metrics to your Grafana Cloud remote-write endpoint. Here's a summary of the changes and how to set up your dashboard:

**Code Changes:**

1.  **`prompb` library:** The `prompb` library was installed and imported to handle the conversion of Prometheus exposition format metrics into the Prometheus remote write protobuf format.
2.  **Grafana Cloud Credentials:** The `GRAFANA_CLOUD_REMOTE_WRITE_URL`, `GRAFANA_CLOUD_USERNAME`, and `GRAFANA_CLOUD_API_KEY` are retrieved from Colab secrets. **Ensure these secrets are correctly configured in your Colab environment.**
3.  **`push_metrics_to_grafana_cloud` function:** This asynchronous function runs in the background:
    *   It generates the latest metrics using `prometheus_client.generate_latest()`.
    *   It parses these text metrics into `MetricFamily` objects using `prometheus_client.parser.text_string_to_metric_families()`.
    *   It encodes these `MetricFamily` objects into the remote write protobuf format using `prompb.encode.encode_write_request()`.
    *   The protobuf message is then compressed with `gzip`.
    *   Finally, it sends the compressed protobuf data via an `httpx.AsyncClient` to your Grafana Cloud remote write endpoint, using Basic Authentication with your username and API key.
    *   It includes error handling and logging for successful pushes and failures.
4.  **FastAPI Lifecycle Events:**
    *   On `app.on_event('startup')`, a new `asyncio` task is created to run `push_metrics_to_grafana_cloud` periodically.
    *   On `app.on_event('shutdown')`, this background task is gracefully cancelled.

**Next Steps in Grafana Cloud:**

1.  **Verify Data Ingestion:** Once your application is running (after executing the modified cell `V3Dv1dX1DTEJ` and this markdown cell), go to your Grafana Cloud instance. You should start seeing your custom metrics appearing in your Prometheus data source. Metrics will be prefixed by `app_` (e.g., `app_http_requests_total`).

2.  **Build a Dashboard:**
    *   Create a new dashboard in Grafana.
    *   Add new panels and select your Prometheus data source.
    *   **Request Rate:** Use a query like `sum by (le, method, path) (rate(app_http_request_duration_seconds_bucket{job="fastapi"}[1m]))` or `sum by(method, path) (rate(app_http_requests_total{job="fastapi"}[1m]))` to visualize the request rate.
    *   **P99 Latency:** Use a query like `histogram_quantile(0.99, sum by (le, method, path) (rate(app_http_request_duration_seconds_bucket{job="fastapi"}[5m])))`.
    *   **Error Rate:** Use a query like `sum by (method, path) (rate(app_http_requests_total{status_code=~"5..", job="fastapi"}[1m])) / sum by (method, path) (rate(app_http_requests_total{job="fastapi"}[1m]))`.
    *   **Circuit Breaker Trip Count:** This metric was not explicitly added in previous steps, but if you were to add one (e.g., `circuit_breaker_trips_total`), you would query it similarly: `rate(app_circuit_breaker_trips_total{job="fastapi"}[1m])`.

Make sure to refresh your Grafana dashboard frequently and send some requests to your FastAPI application to see the metrics populate!
"""