# -*- coding: utf-8 -*-
"""Multi-tool_chaining and Redis event queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xAa_5FzA4hP20miHEscM4j8Q8364E8h

#Multi-tool Agent Chaining + Redis Event Queue

Here the agent does real orchestration: it chains tools to place an order — check_inventory → create_order → send_confirmation — mixing synchronous tools (SQLite reads/writes) with an asynchronous one (enqueue an email job onto a Redis Stream, handled later by a separate worker via a consumer group).

Runs entirely in Colab: fakeredis provides XADD / XREADGROUP, SQLite is built in.

Patterns (from the deck): routing (pick the right tool), prompt chaining (feed one tool's output into the next), parallel reads, and the sync-vs-async boundary — slow side-effects go on a queue so the agent turn stays fast.

Step 1 — Install & configure
"""

!pip install -q anthropic>=0.26.0 fakeredis 2>/dev/null # Explicitly update anthropic
import os, getpass
if not os.environ.get('ANTHROPIC_API_KEY'):
    try:
        from google.colab import userdata
        os.environ['ANTHROPIC_API_KEY'] = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        pass
if not os.environ.get('ANTHROPIC_API_KEY'):
    os.environ['ANTHROPIC_API_KEY'] = str(getpass.getpass('ANTHROPIC_API_KEY (blank = offline mock): '))
LIVE = bool(os.environ.get('ANTHROPIC_API_KEY'))
MODEL = 'claude-sonnet-4-6'
print('LIVE mode' if LIVE else 'OFFLINE mock mode')

"""#Step 2 — SQLite orders + inventory database
Two tables: inventory (stock per SKU) and orders (what we create). All access is through parameterised SQL — never string-formatted — and reads are row-limited.

"""

import sqlite3
db = sqlite3.connect(':memory:', check_same_thread=False)
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('inventory seeded')

"""##Step 3 — A Redis Stream as the email job queue
send_confirmation won't send email inline (slow, can fail). It enqueues a job with XADD and returns a job_id immediately. A worker later reads with XREADGROUP (a consumer group gives us at-least-once delivery + acks) and writes the result back to a jobresult:<id> key.

"""

import fakeredis, json, time, uuid
r = fakeredis.FakeStrictRedis()
STREAM = 'emails'
GROUP  = 'mailers'
try:
    r.xgroup_create(STREAM, GROUP, id='0', mkstream=True)
except Exception as e:
    print('group exists:', e)

def enqueue_email(to, subject, body):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

print('queue ready; sample job id ->', enqueue_email('a@x.com', 'hi', 'test'))

"""##Step 4 — The worker (consumer group)
In production this is a separate process. Here we drain the stream on demand. Each message is processed, the result stored, and the message acked with XACK so it isn't redelivered.

"""

def run_worker(max_msgs=10):
    processed = 0
    resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            # … here you'd call a real email provider …
            r.set(f"jobresult:{f['job_id']}", 'sent')
            r.xack(STREAM, GROUP, msg_id)
            processed += 1
    return processed

print('worker processed', run_worker(), 'job(s)')

"""#Step 5 — Tool functions (sync + async)
check_inventory and create_order are synchronous — they touch SQLite and return immediately. create_order re-checks stock and decrements it in one transaction (guarding against overselling). send_confirmation is asynchronous — it enqueues and returns a job_id. check_job polls a result.


"""

def check_inventory(sku: str):
    row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not row:
        return {'error': f'unknown sku {sku}'}
    return {'sku': row[0], 'name': row[1], 'qty': row[2], 'price': row[3]}

def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}
    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, round(price*qty, 2), 'created'))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': round(price*qty, 2)}

def send_confirmation(to: str, order_id: int):
    job_id = enqueue_email(to, f'Order {order_id} confirmed', f'Your order {order_id} is on its way.')
    return {'job_id': job_id, 'status': 'queued'}

def check_job(job_id: str):
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

# quick manual chain
inv = check_inventory('KB-01'); print(inv)
od  = create_order('KB-01', 2);  print(od)
jb  = send_confirmation('asha@x.com', od['order_id']); print(jb)
run_worker(); print(check_job(jb['job_id']))

"""##Step 6 — Tool schemas + dispatch"""

TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
]
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job}

def run_tool(name, args):
    fn = DISPATCH.get(name)
    if not fn: return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        return out, isinstance(out, dict) and 'error' in out
    except Exception as e:
        return {'error': repr(e)}, True
print('tools ready')

"""##Step 7 — The orchestrating agent loop
Same stop_reason loop as Colab 1, but now the model chains several tools in one turn and we drain the worker afterwards. The offline mock scripts the full chain so the notebook runs without a key.

"""

import json
SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order, ' +
  'then send_confirmation with the returned order_id. After sending confirmation, ' +
  'you MUST use the verify_order tool with the order_id to confirm the order details ' +
  'and its status before reporting success. Report the order total and the email job status. ' +
  'If stock is insufficient, say so and do not create the order.'
)

def agent(user_text, max_steps=8, verbose=True):
    if not LIVE:
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation → verify_order')
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        # Removed run_worker() from mock path, as it's now a background thread
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        vr,_  = run_tool('verify_order', {'order_id':od['order_id']})
        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}. Verification: {vr['status']}."

    from anthropic import Anthropic
    A = Anthropic()
    messages = [{'role':'user','content':user_text}]
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages)
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            # Removed run_worker() from LIVE path, as it's now a background thread
            continue
        return ''.join(b.text for b in resp.content if b.type=='text')
    return '(max steps reached)'

print(agent('Order one 4K monitor (SKU MON-4) and email asha@x.com the confirmation.'))

"""##Step 8 — Show the resulting state"""

print('Orders table:')
for row in db.execute('SELECT id,sku,qty,total,status FROM orders').fetchall():
    print(' ', row)
print('Remaining stock:')
for row in db.execute('SELECT sku,qty FROM inventory').fetchall():
    print(' ', row)
# Try an out-of-stock order to see graceful failure
print('Out-of-stock attempt:', run_tool('create_order', {'sku':'HUB-2','qty':1}))

"""Extension_Tasks

1.Dead-letter & retry. Make the worker fail jobs whose to is invalid; move them to an emails:dlq stream after N retries instead of acking. Add a tool to inspect the DLQ.
"""

# Constants for DLQ and retries
DLQ_STREAM = 'emails:dlq'
MAX_RETRIES = 3

# Helper for email validation
def is_valid_email(email):
    return '@' in email and '.' in email.split('@')[-1]

# --- Modified enqueue_email function (from JGSxnVtPVZSZ) ---
def enqueue_email(to, subject, body, retries=0):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body, 'retries': str(retries)})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

# --- Modified run_worker function (from XkU3qkSLViNs) ---
def run_worker(max_msgs=10):
    processed = 0
    resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs, block=500) # Added block to avoid busy-waiting
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            job_id = f['job_id']
            to = f['to']
            current_retries = int(f.get('retries', 0))

            # Simulate email sending failure based on invalid email address
            if not is_valid_email(to):
                current_retries += 1
                if current_retries < MAX_RETRIES:
                    # Re-enqueue with incremented retry count
                    r.xadd(STREAM, {**f, 'retries': str(current_retries)})
                    r.set(f'jobresult:{job_id}', f'retrying (attempt {current_retries}/{MAX_RETRIES})')
                    print(f"Job {job_id} for '{to}' retrying: {current_retries}/{MAX_RETRIES}")
                else:
                    # Move to DLQ
                    r.xadd(DLQ_STREAM, f)
                    r.set(f'jobresult:{job_id}', 'dead-lettered')
                    print(f"Job {job_id} for '{to}' dead-lettered after {current_retries} retries")
                r.xack(STREAM, GROUP, msg_id) # Acknowledge from main stream
            else:
                # --- Real email sending logic would go here ---
                # For now, just mark as sent
                r.set(f"jobresult:{job_id}", 'sent')
                r.xack(STREAM, GROUP, msg_id)
                processed += 1
                print(f"Job {job_id} for '{to}' sent")
    return processed

# --- New tool to inspect DLQ ---
def inspect_dlq(count=10):
    messages = []
    try:
        # Read messages from the DLQ stream
        resp = r.xrange(DLQ_STREAM, count=count)
        for msg_id, fields in resp:
            messages.append({k.decode(): v.decode() for k, v in fields.items()})
    except Exception as e:
        # DLQ_STREAM might not exist if no messages are dead-lettered yet
        if 'no such key' in str(e).lower():
            return []
        else:
            raise
    return messages

# --- Update TOOLS (from y5R63KRoV3hT) ---
# Re-define TOOLS to include the new inspect_dlq tool
TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
  {'name':'inspect_dlq','description':'Inspect messages in the Dead Letter Queue (DLQ).',
   'input_schema':{'type':'object','properties':{'count':{'type':'integer','description':'Number of messages to retrieve from DLQ.'}},'required':[]}},
]

# --- Update DISPATCH (from y5R63KRoV3hT) ---
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job,
            'inspect_dlq':inspect_dlq}

print('DLQ and retry mechanisms initialized. TOOLS and DISPATCH updated.')

# --- Test cases for DLQ functionality ---
print('\n--- Testing DLQ functionality ---\n')

# Enqueue an email with an invalid address
invalid_email_job = enqueue_email('invalid-email', 'Invalid Email Test', 'This email should go to DLQ')
print(f"Enqueued invalid email job: {invalid_email_job}")

# Run worker multiple times to simulate retries and move to DLQ
print('\nRunning worker to process invalid email job (multiple times for retries):')
for i in range(MAX_RETRIES + 1):
    run_worker()
    status = check_job(invalid_email_job)['status']
    print(f"Attempt {i+1}: Job status - {status}")
    if status == 'dead-lettered':
        break

# Inspect the DLQ
print('\nInspecting DLQ:')
dlq_messages = inspect_dlq()
if dlq_messages:
    for msg in dlq_messages:
        print(f"  DLQ Message: {msg}")
else:
    print('  DLQ is empty.')

# Enqueue a valid email to ensure normal flow still works
valid_email_job = enqueue_email('valid@example.com', 'Valid Email Test', 'This email should be sent')
print(f"\nEnqueued valid email job: {valid_email_job}")
run_worker()
print(f"Valid email job status: {check_job(valid_email_job)['status']}")

"""2.Evaluator / verify step. Add a verify_order tool that re-reads the order and confirms total & status; have the system prompt require it before declaring success (evaluator-optimiser pattern)."""

def verify_order(order_id: int):
    row = db.execute('SELECT id, sku, qty, total, status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    return {'order_id': row[0], 'sku': row[1], 'qty': row[2], 'total': row[3], 'status': row[4]}

# Update TOOLS to include the new verify_order tool
TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
  {'name':'inspect_dlq','description':'Inspect messages in the Dead Letter Queue (DLQ).',
   'input_schema':{'type':'object','properties':{'count':{'type':'integer','description':'Number of messages to retrieve from DLQ.'}},'required':[]}},
  {'name':'verify_order','description':'Verify a created order by re-reading its details from the database.',
   'input_schema':{'type':'object','properties':{'order_id':{'type':'integer','description':'The ID of the order to verify.'}},'required':['order_id']}}
]

# Update DISPATCH to include the new verify_order tool
DISPATCH['verify_order'] = verify_order

print('verify_order tool added. TOOLS and DISPATCH updated.')

"""3.Orchestrator-worker split. Move run_worker() into a background threading.Thread loop so the agent never calls it directly; the queue truly decouples them."""

import threading
import time

# Flag to signal the worker thread to stop
worker_stop_event = threading.Event()

def worker_thread_loop():
    """Continuously runs the email worker until a stop event is set."""
    print("[Worker Thread]: Starting background email worker...")
    while not worker_stop_event.is_set():
        try:
            processed_count = run_worker() # run_worker is already defined
            if processed_count > 0:
                print(f"[Worker Thread]: Processed {processed_count} email job(s).")
        except Exception as e:
            print(f"[Worker Thread]: Error in worker: {e}")
        # Wait for a short period or until signaled to stop
        worker_stop_event.wait(timeout=1) # Check every 1 second
    print("[Worker Thread]: Background email worker stopped.")

# Start the worker thread
worker_thread = threading.Thread(target=worker_thread_loop, daemon=True)
worker_thread.start()

# Function to stop the worker thread (optional, for cleanup if needed)
def stop_background_worker():
    print("Signaling background worker to stop...")
    worker_stop_event.set()
    worker_thread.join(timeout=5) # Give it some time to finish
    if worker_thread.is_alive():
        print("Warning: Worker thread did not stop gracefully.")

# Register the stop function to run on exit (e.g., when Colab runtime stops)
import atexit
atexit.register(stop_background_worker)

print("Background email worker thread initialized and started.")

"""4.Human-in-the-loop gate. For orders above a value threshold, have create_order return {'status':'needs_approval'} and require an approve_order(order_id) tool call before fulfilment."""

APPROVAL_THRESHOLD = 500.0 # Define a threshold for human approval

# --- Modified create_order function (from BuIjAe8AVtjC) ---
def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}

    total = round(price * qty, 2)
    status = 'created'
    if total >= APPROVAL_THRESHOLD:
        status = 'needs_approval'
        print(f"Order for {sku} with total ${total} needs approval.")

    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, total, status))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': total, 'status': status}

# --- New tool to approve orders ---
def approve_order(order_id: int):
    current_order = db.execute('SELECT status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not current_order:
        return {'error': f'Order {order_id} not found'}
    if current_order[0] != 'needs_approval':
        return {'error': f'Order {order_id} does not need approval; current status: {current_order[0]}'}
    db.execute('UPDATE orders SET status=? WHERE id=?', ('created', order_id))
    db.commit()
    return {'order_id': order_id, 'status': 'approved'}

# --- Update TOOLS (from HkThw7BYXo7O) ---
TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':"Create an order for a SKU and quantity. Fails if stock is insufficient. For orders above a certain value, the status might be 'needs_approval'.",
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
  {'name':'inspect_dlq','description':'Inspect messages in the Dead Letter Queue (DLQ).',
   'input_schema':{'type':'object','properties':{'count':{'type':'integer','description':'Number of messages to retrieve from DLQ.'}},'required':[]}},
  {'name':'verify_order','description':'Verify a created order by re-reading its details from the database.',
   'input_schema':{'type':'object','properties':{'order_id':{'type':'integer','description':'The ID of the order to verify.'}},'required':['order_id']}},
  {'name':'approve_order','description':"Approve an order that is currently in 'needs_approval' status.",
   'input_schema':{'type':'object','properties':{'order_id':{'type':'integer','description':'The ID of the order to approve.'}},'required':['order_id']}}
]

# --- Update DISPATCH (from HkThw7BYXo7O) ---
DISPATCH['create_order'] = create_order # Re-assign the modified create_order
DISPATCH['approve_order'] = approve_order

print(f"Human-in-the-loop approval system initialized with threshold: ${APPROVAL_THRESHOLD}")

# --- Test cases for human-in-the-loop functionality ---
print('\n--- Testing Human-in-the-loop functionality ---\n')

# Create a low-value order (should be 'created' immediately)
low_value_order = create_order('KB-01', 1) # Price 129.0
print(f"Low-value order: {low_value_order}")

# Create a high-value order (should be 'needs_approval')
high_value_order = create_order('MON-4', 2) # Price 410.0 * 2 = 820.0
print(f"High-value order: {high_value_order}")

# Try to approve the high-value order
if high_value_order and high_value_order.get('status') == 'needs_approval':
    approved_status = approve_order(high_value_order['order_id'])
    print(f"Approval attempt for high-value order: {approved_status}")
    # Verify its final status
    verified_high_value_order = verify_order(high_value_order['order_id'])
    print(f"Verified high-value order after approval: {verified_high_value_order}")

print('\nOrders table after human-in-the-loop tests:')
for row in db.execute('SELECT id,sku,qty,total,status FROM orders').fetchall():
    print(' ', row)

"""5.Trace spans. Wrap run_tool to record {tool, args, ms, ok} per call; print a per-turn trace table."""

import time
import json
from anthropic import Anthropic # Re-import Anthropic for the redefined agent function

TOOL_TRACES = [] # Global list to store traces for a single agent turn

def _print_trace_table():
    """Prints a formatted table of recorded tool call traces."""
    if not TOOL_TRACES:
        print('\n--- Tool Call Trace (No tool calls in this turn) ---')
        return

    print('\n--- Tool Call Trace ---')
    # Determine column widths dynamically for better formatting
    max_tool_len = max(len(t['tool']) for t in TOOL_TRACES) if TOOL_TRACES else 4
    max_args_len = max(len(str(t['args'])) for t in TOOL_TRACES) if TOOL_TRACES else 4

    # Ensure minimum width for readability
    max_tool_len = max(max_tool_len, len('Tool'))
    max_args_len = max(max_args_len, len('Args'))

    # Header
    header_format = f"{{:<{max_tool_len}}} | {{:<{max_args_len}}} | {{:>6}} | {{:>4}}"
    print(header_format.format('Tool', 'Args', 'MS', 'OK'))
    print(f"{{:-<{max_tool_len}}}-+-{{:-<{max_args_len}}}-+-{{:->6}}-+-{{:->4}}".format('', '', '', ''))

    # Rows
    for trace in TOOL_TRACES:
        tool_name = trace['tool']
        args_str = str(trace['args'])
        ms = trace['ms']
        ok = '✅' if trace['ok'] else '❌'
        print(header_format.format(tool_name, args_str, f"{ms:.2f}", ok))
    print('---------------------\n')

# Redefine run_tool with tracing capabilities
def run_tool(name, args):
    start_time = time.perf_counter()
    out, is_err = {}, True # Initialize output and error status

    fn = DISPATCH.get(name) # DISPATCH is expected to be a global variable from previous cells
    if not fn:
        out = {'error': f'unknown tool {name}'}
        is_err = True
    else:
        try:
            out = fn(**args)
            # A tool result is considered an error if it's a dict and contains an 'error' key
            is_err = isinstance(out, dict) and 'error' in out
        except Exception as e:
            out = {'error': repr(e)}
            is_err = True

    end_time = time.perf_counter()
    elapsed_ms = round((end_time - start_time) * 1000, 2)

    TOOL_TRACES.append({'tool': name, 'args': args, 'ms': elapsed_ms, 'ok': not is_err})

    return out, is_err

# Redefine agent function to incorporate tracing and print trace table
def agent(user_text, max_steps=8, verbose=True):
    global TOOL_TRACES
    TOOL_TRACES = [] # Clear traces for each new agent turn

    if not LIVE: # LIVE is expected to be a global variable
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation → verify_order')
        # Use the *newly defined* run_tool
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        vr,_  = run_tool('verify_order', {'order_id':od['order_id']})

        _print_trace_table() # Print trace table at the end of the turn

        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}. Verification: {vr['status']}."

    A = Anthropic() # Anthropic is re-imported at the top of this cell
    messages = [{'role':'user','content':user_text}]
    response_text = ''
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages) # MODEL, SYSTEM, TOOLS are globals
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    # Use the *newly defined* run_tool
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            continue
        response_text = ''.join(b.text for b in resp.content if b.type=='text')
        break # Exit loop if not tool_use

    _print_trace_table() # Print trace table at the end of the turn

    return response_text

# Demonstrate the new tracing with an agent call
print("\n--- Running agent with tracing ---\n")
# Using the same prompt as in FD9EZd1LWB0M to test the agent
print(agent('Order one 4K monitor (SKU MON-4) and email asha@x.com the confirmation.'))

print('Current stock for MON-4:')
row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', ('MON-4',)).fetchone()
if row:
    print(f"  SKU: {row[0]}, Name: {row[1]}, Quantity: {row[2]}, Price: {row[3]}")
else:
    print('  MON-4 not found in inventory.')