# -*- coding: utf-8 -*-
"""FAQ_RAG_BOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sef7DND_wb67xxQA43pxPdSnJgTvgNMa
"""

!pip install faiss-cpu
!pip install groq
!pip install scikit-learn
import os
import faiss
import numpy as np
from dotenv import load_dotenv
from groq import Groq
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.preprocessing import normalize
load_dotenv()
FAQS = [
    "Q: What are the library hours? A: The library is open from 9 AM to 9 PM, Monday through Friday, and 10 AM to 5 PM on weekends.",
    "Q: How can I borrow a book? A: You can borrow books by presenting your library card at the circulation desk.",
    "Q: What is the overdue fine policy? A: Overdue fines are $0.25 per day per item, with a maximum of $5.00 per item.",
    "Q: Do you offer computer access? A: Yes, we have public computers available for use with a library card. Sessions are limited to one hour.",
    "Q: How do I reserve a meeting room? A: Meeting rooms can be reserved online through our website or in person at the information desk.",
    "Q: Can I print documents at the library? A: Yes, printing is available for $0.10 per page for black and white, and $0.50 for color.",
    "Q: How do I get a library card? A: Bring a valid photo ID and proof of address to the circulation desk to apply for a library card.",
    "Q: Do you have Wi-Fi? A: Yes, free Wi-Fi is available throughout the library. No password is required.",
    "Q: What events are happening this month? A: Check our online calendar or the bulletin board near the entrance for a list of upcoming events.",
    "Q: How can I donate books? A: We accept donations of gently used books at the front desk during library hours."
]

vectorizer = HashingVectorizer(n_features=384, alternate_sign=False, norm=None)
faq_vectors = normalize(vectorizer.transform(FAQS), norm="l2").astype(np.float32).toarray()
index = faiss.IndexFlatIP(faq_vectors.shape[1])
index.add(faq_vectors)

def retrieve(query, top_k=2):
    query_vector = normalize(vectorizer.transform([query]), norm="l2").astype(np.float32).toarray()
    scores, indexes = index.search(query_vector, top_k)
    return [(FAQS[i], float(score)) for i, score in zip(indexes[0], scores[0])]

def generate_answer(query, matches):
    context = "\n".join(f"- {faq} (score={score:.3f})" for faq, score in matches)
    key = os.getenv("GROQ_API_KEY", "")
    if not key:
        return f"Offline answer:\n{matches[0][0]}\n\nRetrieved:\n{context}"
    client = Groq(api_key=key)
    try:
        response = client.chat.completions.create(
            model=os.getenv("GROQ_MODEL", "llama-3.1-8b-instant"),
            messages=[
                {"role": "system", "content": "Answer concisely using only the retrieved FAQs."},
                {"role": "user", "content": f"User query: {query}\nRetrieved FAQs:\n{context}"},
            ],
            temperature=0.1,
        )
        return response.choices[0].message.content or ""
    except Exception as exc:
        return f"Groq unavailable ({exc}). Offline answer:\n{matches[0][0]}\n\nRetrieved:\n{context}"


print("Smart FAQ Bot. Type 'exit' to quit.")
while True:
    user_query = input("\nYou: ").strip()
    if user_query.lower() == "exit":
        break
    results = retrieve(user_query)
    print("\nBot:", generate_answer(user_query, results))
    print("Top scores:", ", ".join(f"{score:.3f}" for _, score in results))