# -*- coding: utf-8 -*-
"""Semantic Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0J-bSi3OSPM4G3pzfaxdR8cajRo0f9T

## Hybrid Semantic Search for PDF Content
"""

# Install required libraries
!pip install -q pypdf sentence-transformers rank-bm25

import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, util
from pypdf import PdfReader
import re

"""### 1. Extract Text from PDF"""

pdf_path = '/content/12153_INTRODUCTION TO MOBILE PHONE.pdf'

def extract_text_from_pdf(pdf_path):
    reader = PdfReader(pdf_path)
    text_content = []
    for page in reader.pages:
        page_text = page.extract_text()
        # Clean up text by removing extra spaces and newlines
        cleaned_text = re.sub(r'\s+', ' ', page_text).strip()
        if cleaned_text:
            text_content.append(cleaned_text)
    return text_content

corpus = extract_text_from_pdf(pdf_path)
print(f"Loaded {len(corpus)} pages from the PDF document.")

# Display first few pages to verify
# for i, page in enumerate(corpus[:3]):
#     print(f"\n--- Page {i+1} ---")
#     print(page[:500] + '...' if len(page) > 500 else page)

"""### 2. Initialize Sparse Search (BM25)"""

# Tokenize corpus for BM25 processing
tokenized_corpus = [doc.lower().split(" ") for doc in corpus]
bm25 = BM25Okapi(tokenized_corpus)

def sparse_search(query, top_n=5):
    """Executes keyword lookup and returns sorted document indices and raw scores."""
    tokenized_query = query.lower().split(" ")
    scores = bm25.get_scores(tokenized_query)
    # Sort indices by score descending
    top_indices = np.argsort(scores)[::-1][:top_n]

    # Return list of tuples: (doc_id, score)
    return [(idx, scores[idx]) for idx in top_indices if scores[idx] > 0]

"""### 3. Initialize Dense Search (SentenceTransformer)"""

# Initialize a lightweight, high-performance bi-encoder model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Generate dense vector embeddings for the entire corpus
corpus_embeddings = embedding_model.encode(corpus, convert_to_tensor=True)

def dense_search(query, top_n=5):
    """Executes semantic search via cosine similarity and returns sorted indices and scores."""
    query_embedding = embedding_model.encode(query, convert_to_tensor=True)

    # Calculate cosine similarity matrix against all corpus documents
    cos_scores = util.cos_sim(query_embedding, corpus_embeddings)[0]

    # Sort top elements
    top_results = np.argsort(cos_scores.cpu().numpy())[::-1][:top_n]

    return [(int(idx), float(cos_scores[idx])) for idx in top_results]

"""### 4. Reciprocal Rank Fusion (RRF)"""

def reciprocal_rank_fusion(sparse_results, dense_results, k=60, top_n=3):
    """
    Fuses rankings from separate systems using the Reciprocal Rank Fusion formula.
    Inputs are expected to be lists of tuples: (doc_id, score) sorted by relevance.
    """
    rrf_scores = {}

    # Process sparse rankings
    for rank, (doc_id, _) in enumerate(sparse_results):
        # rank starts at 0, so rank position is rank + 1
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + (rank + 1))

    # Process dense rankings
    for rank, (doc_id, _) in enumerate(dense_results):
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + (rank + 1))

    # Sort documents based on their combined RRF metrics
    fused_rankings = sorted(rrf_scores.items(), key=lambda item: item[1], reverse=True)

    return fused_rankings[:top_n]

"""### 5. Hybrid Search Engine"""

def hybrid_search_engine(query, top_n=3):
    """Orchestrates both systems and fuses the output."""
    # 1. Gather deep recall arrays from both engines
    sparse_res = sparse_search(query, top_n=len(corpus)) # Retrieve more results for RRF
    dense_res = dense_search(query, top_n=len(corpus)) # Retrieve more results for RRF

    # 2. Fuse the rankings using RRF
    hybrid_res = reciprocal_rank_fusion(sparse_res, dense_res, k=60, top_n=top_n)

    # 3. Print pretty outputs for comparison
    print(f"\n==== Query: '{query}' ====")
    if not hybrid_res:
        print("No relevant results found.")
        return []

    for rank, (doc_id, rrf_score) in enumerate(hybrid_res):
        print(f"\n[Rank {rank + 1}] (RRF Score: {rrf_score:.4f})")
        print(f"Source Page: {doc_id + 1}") # Page numbers are 1-indexed
        print(f"Content: {corpus[doc_id][:500]}...") # Display first 500 characters of the page

    return hybrid_res

"""### 6. Perform a Search"""

# Enter your query below
query = "what is a mobile phone?"
hybrid_search_engine(query, top_n=5)

"""### 7. Ground Truth Dataset for Evaluation

To evaluate the effectiveness of our hybrid search engine, we need a **ground truth** dataset. This dataset will contain a set of queries and, for each query, the actual relevant page numbers (documents) from your PDF. You will need to manually review the PDF and identify which pages are relevant for specific queries.

Edit the `ground_truth` dictionary below with your queries and the corresponding 1-indexed page numbers.
"""

# Example ground truth dataset structure
# You will need to manually fill this with your own queries and their relevant page numbers.
# Remember: page numbers are 1-indexed in the PDF, so adjust if your corpus is 0-indexed.

ground_truth = {
    "What are the advantages of a basic phone?": [2],  # Query maps to relevant pages (e.g., Page 2)
    "mobile phone features": [1, 3, 4], # Query maps to relevant pages (e.g., Pages 1, 3, 4)
    "What is a Smartphone?": [3],
    "uses of mobile phone": [5]
}

print("Ground truth dataset created. Please review and populate it with your specific queries and relevant page numbers.")

"""### 8. Evaluation Metrics: MRR and NDCG

We will use **Mean Reciprocal Rank (MRR)** and **Normalized Discounted Cumulative Gain (NDCG)** to quantify the performance of our search engine.

*   **Mean Reciprocal Rank (MRR)**: Measures the ranking quality of the first relevant document. A higher MRR (closer to 1.0) means relevant documents are found at higher ranks.

    $	ext{MRR} = \frac{1}{|Q|} \sum_{q=1}^{|Q|} \frac{1}{\text{rank}_q}$

*   **Normalized Discounted Cumulative Gain (NDCG)**: Measures the overall ranking quality, considering the relevance of documents and their positions in the results list. It's especially useful when relevance can be graded (though here we'll use binary relevance).

    $	ext{DCG}_p = \sum_{i=1}^{p} \frac{2^{\text{rel}_i} - 1}{\log_2(i+1)}$

    $	ext{IDCG}_p = \sum_{i=1}^{p} \frac{2^{\text{rel}_{i, \text{ideal}}} - 1}{\log_2(i+1)}$

    $	ext{NDCG}_p = \frac{\text{DCG}_p}{\text{IDCG}_p}$
"""

def calculate_mrr(ground_truth, search_function, corpus):
    """Calculates Mean Reciprocal Rank (MRR)."""
    reciprocal_ranks = []
    for query, relevant_page_numbers in ground_truth.items():
        if not relevant_page_numbers: # Skip if no relevant documents defined
            continue

        # Convert 1-indexed page numbers to 0-indexed document IDs for comparison with search results
        relevant_doc_ids = [p - 1 for p in relevant_page_numbers]

        results = search_function(query, top_n=len(corpus)) # Get all results to find first relevant
        found_first_relevant = False
        for rank, (doc_id, _) in enumerate(results):
            if doc_id in relevant_doc_ids:
                reciprocal_ranks.append(1 / (rank + 1))
                found_first_relevant = True
                break
        if not found_first_relevant: # If no relevant document was found in results
            reciprocal_ranks.append(0)

    return np.mean(reciprocal_ranks) if reciprocal_ranks else 0

def calculate_ndcg(ground_truth, search_function, corpus, k=5):
    """Calculates Normalized Discounted Cumulative Gain (NDCG@k)."""
    ndcg_scores = []
    for query, relevant_page_numbers in ground_truth.items():
        if not relevant_page_numbers: # Skip if no relevant documents defined
            continue

        # Convert 1-indexed page numbers to 0-indexed document IDs for comparison with search results
        relevant_doc_ids = [p - 1 for p in relevant_page_numbers]

        # Get search results (note: hybrid_search_engine prints, but we need the returned list)
        # Temporarily redirect print to suppress output during evaluation if preferred
        # For now, we assume search_function returns the raw results without printing
        search_results = search_function(query, top_n=k)
        # The hybrid_search_engine function prints to console, let's call it here so it doesn't print during evaluation
        # A better approach would be to refactor hybrid_search_engine to separate printing from returning results.
        # For this context, we will assume it returns the list of (doc_id, score) directly.

        # Calculate DCG
        dcg = 0.0
        for i, (doc_id, _) in enumerate(search_results):
            if doc_id in relevant_doc_ids:
                # Assuming binary relevance (1 if relevant, 0 if not)
                relevance = 1
            else:
                relevance = 0
            dcg += (2**relevance - 1) / np.log2(i + 2) # i + 2 because log2(1) is 0

        # Calculate IDCG (Ideal DCG)
        # Get relevance scores for top k ideal documents
        # Assuming all relevant docs have relevance 1
        ideal_relevance_scores = [1] * len(relevant_doc_ids)
        ideal_relevance_scores = sorted(ideal_relevance_scores, reverse=True)[:k]

        idcg = 0.0
        for i, relevance in enumerate(ideal_relevance_scores):
            idcg += (2**relevance - 1) / np.log2(i + 2)

        if idcg > 0:
            ndcg_scores.append(dcg / idcg)
        else:
            ndcg_scores.append(0) # If there are no relevant documents in ideal top k, NDCG is 0

    return np.mean(ndcg_scores) if ndcg_scores else 0

print("MRR and NDCG functions defined.")

"""### 9. Evaluate the Hybrid Search Engine"""

# To perform the evaluation, we need to pass a search function that returns just the ranked list of (doc_id, score).
# The current `hybrid_search_engine` prints results. For evaluation, we need a silent version.
# Let's create a wrapper function for evaluation that does not print:

def hybrid_search_engine_for_evaluation(query, top_n=3):
    sparse_res = sparse_search(query, top_n=len(corpus))
    dense_res = dense_search(query, top_n=len(corpus))
    hybrid_res = reciprocal_rank_fusion(sparse_res, dense_res, k=60, top_n=top_n)
    return hybrid_res

mrr_score = calculate_mrr(ground_truth, hybrid_search_engine_for_evaluation, corpus)
ndcg_score = calculate_ndcg(ground_truth, hybrid_search_engine_for_evaluation, corpus)

print(f"\nMean Reciprocal Rank (MRR): {mrr_score:.4f}")
print(f"Normalized Discounted Cumulative Gain (NDCG@5): {ndcg_score:.4f}")