# -*- coding: utf-8 -*-
"""RAG_METRICS_AND_LATENCY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzqklIwipKkHbA_Utp7G011oPRPNMgqz

**RAG Metrics and Latency Evaluation**
"""

from __future__ import annotations

import argparse
import json
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path

BASE_DIR = Path.cwd()
CACHE_DIR = BASE_DIR / ".cache"
CACHE_DIR.mkdir(exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(CACHE_DIR / "matplotlib"))

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import normalize


OUTPUT_DIR = BASE_DIR / "output"
PLOTS_DIR = OUTPUT_DIR / "plots"
TOP_K = 3
EMBEDDING_DIM = 512


@dataclass
class Article:
    title: str
    content: str


@dataclass
class QueryCase:
    query_id: str
    query: str
    expected_title: str
    reference_answer: str


@dataclass
class RetrievedChunk:
    title: str
    content: str
    score: float


ARTICLES = [
    Article(
        title="Retrieval-Augmented Generation",
        content=(
            "Retrieval-Augmented Generation combines search with a language model. "
            "Documents are split into chunks, embedded into vectors, and stored in an index. "
            "At question time, the query is embedded, relevant chunks are retrieved, and the "
            "language model answers using only the retrieved context. RAG reduces hallucination "
            "by grounding the answer in external evidence."
        ),
    ),
    Article(
        title="Vector Search",
        content=(
            "Vector search represents text as numeric embeddings and finds similar content by "
            "nearest-neighbour search. Similarity can be measured with cosine similarity, dot "
            "product, or Euclidean distance. Vector search is useful for semantic search because "
            "it can match meaning even when exact keywords differ."
        ),
    ),
    Article(
        title="FAISS",
        content=(
            "FAISS is an open-source similarity search library from Meta. It can build local "
            "vector indexes and perform fast nearest-neighbour search. FAISS is useful for small "
            "RAG prototypes because it runs in process and does not require a cloud database."
        ),
    ),
    Article(
        title="Azure AI Search",
        content=(
            "Azure AI Search is a managed search service that supports keyword search, vector "
            "search, and hybrid retrieval. It can index enterprise documents, store metadata, "
            "and retrieve relevant chunks for RAG pipelines. Azure retrieval latency is often "
            "stable compared with language model generation time."
        ),
    ),
    Article(
        title="Answer Evaluation",
        content=(
            "Answer relevance measures how well a generated response addresses the question. "
            "Faithfulness measures whether answer claims are supported by retrieved context. "
            "Context precision measures how many retrieved chunks are relevant to the query. "
            "Together these metrics show whether latency is producing useful answer quality."
        ),
    ),
    Article(
        title="Latency in RAG",
        content=(
            "RAG latency usually includes query embedding time, retrieval time, and answer "
            "generation time. Embedding and retrieval are often short and stable. Generation "
            "latency can vary widely because longer answers, more context, and complex reasoning "
            "require more model tokens and more processing time."
        ),
    ),
]


QUERY_CASES = [
    QueryCase(
        query_id="Q1",
        query="How does RAG reduce hallucination?",
        expected_title="Retrieval-Augmented Generation",
        reference_answer="RAG reduces hallucination by retrieving external context and grounding the generated answer in that evidence.",
    ),
    QueryCase(
        query_id="Q2",
        query="Why is FAISS useful for local RAG prototypes?",
        expected_title="FAISS",
        reference_answer="FAISS is useful because it builds local vector indexes and performs fast nearest-neighbour search without a cloud database.",
    ),
    QueryCase(
        query_id="Q3",
        query="What stages contribute to RAG latency variation?",
        expected_title="Latency in RAG",
        reference_answer="RAG latency includes embedding, retrieval, and generation, but generation varies most because answer length and reasoning complexity change.",
    ),
    QueryCase(
        query_id="Q4",
        query="What does answer relevance measure?",
        expected_title="Answer Evaluation",
        reference_answer="Answer relevance measures how well the generated response addresses the user question.",
    ),
    QueryCase(
        query_id="Q5",
        query="How does Azure AI Search support retrieval?",
        expected_title="Azure AI Search",
        reference_answer="Azure AI Search supports keyword, vector, and hybrid retrieval over indexed enterprise documents and metadata.",
    ),
    QueryCase(
        query_id="Q6",
        query="What is context precision in RAG evaluation?",
        expected_title="Answer Evaluation",
        reference_answer="Context precision measures the proportion of retrieved chunks that are relevant to the query.",
    ),
]


class LocalHashingEmbedder:
    def __init__(self, dimensions: int) -> None:
        self.vectorizer = HashingVectorizer(
            n_features=dimensions,
            alternate_sign=False,
            norm=None,
            stop_words="english",
        )

    def embed_documents(self, texts: list[str]) -> np.ndarray:
        matrix = self.vectorizer.transform(texts)
        normalized = normalize(matrix, norm="l2", copy=False)
        return normalized.astype(np.float32).toarray()

    def embed_query(self, query: str) -> np.ndarray:
        return self.embed_documents([query])


def token_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def content_words(text: str) -> set[str]:
    stop_words = {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "because",
        "by",
        "for",
        "from",
        "how",
        "in",
        "is",
        "it",
        "of",
        "on",
        "or",
        "that",
        "the",
        "to",
        "what",
        "when",
        "where",
        "which",
        "why",
        "with",
    }
    return {
        word
        for word in re.findall(r"[a-z0-9]+", text.lower())
        if word not in stop_words and len(word) > 2
    }


def retrieve(
    query: str,
    articles: list[Article],
    embedder: LocalHashingEmbedder,
    article_vectors: np.ndarray,
    top_k: int,
) -> tuple[list[RetrievedChunk], float, float]:
    embedding_started = time.perf_counter()
    query_vector = embedder.embed_query(query)
    embedding_latency_ms = (time.perf_counter() - embedding_started) * 1000

    retrieval_started = time.perf_counter()
    similarities = cosine_similarity(query_vector, article_vectors)[0]
    ranked_indexes = np.argsort(similarities)[::-1][:top_k]
    retrieved = [
        RetrievedChunk(
            title=articles[index].title,
            content=articles[index].content,
            score=float(similarities[index]),
        )
        for index in ranked_indexes
    ]
    retrieval_latency_ms = (time.perf_counter() - retrieval_started) * 1000

    return retrieved, embedding_latency_ms, retrieval_latency_ms


def generate_grounded_answer(query: str, retrieved_chunks: list[RetrievedChunk]) -> tuple[str, float]:
    generation_started = time.perf_counter()
    query_terms = content_words(query)
    selected_sentences: list[str] = []

    for chunk in retrieved_chunks:
        sentences = re.split(r"(?<=[.!?])\s+", chunk.content)
        for sentence in sentences:
            if content_words(sentence) & query_terms:
                selected_sentences.append(sentence.strip())

    if not selected_sentences:
        selected_sentences = [retrieved_chunks[0].content.split(".")[0].strip() + "."]

    answer = " ".join(selected_sentences[:3])

    # Small deterministic delay so generation latency is visible in charts.
    time.sleep(min(0.03, 0.002 * token_count(answer)))
    generation_latency_ms = (time.perf_counter() - generation_started) * 1000
    return answer, generation_latency_ms


def answer_relevance(query: str, answer: str, embedder: LocalHashingEmbedder) -> float:
    vectors = embedder.embed_documents([query, answer])
    return round(float(cosine_similarity([vectors[0]], [vectors[1]])[0][0]), 4)


def faithfulness(answer: str, retrieved_chunks: list[RetrievedChunk]) -> float:
    answer_terms = content_words(answer)
    context_terms = content_words(" ".join(chunk.content for chunk in retrieved_chunks))
    if not answer_terms:
        return 0.0
    return round(len(answer_terms & context_terms) / len(answer_terms), 4)


def context_precision(query_case: QueryCase, retrieved_chunks: list[RetrievedChunk]) -> float:
    reference_terms = content_words(query_case.reference_answer)
    relevant_count = 0

    for chunk in retrieved_chunks:
        title_match = chunk.title.lower() == query_case.expected_title.lower()
        overlap = len(content_words(chunk.content) & reference_terms)
        if title_match or overlap >= 3:
            relevant_count += 1

    return round(relevant_count / len(retrieved_chunks), 4) if retrieved_chunks else 0.0


def evaluate_query(
    query_case: QueryCase,
    articles: list[Article],
    embedder: LocalHashingEmbedder,
    article_vectors: np.ndarray,
) -> dict:
    retrieved, embedding_latency_ms, retrieval_latency_ms = retrieve(
        query=query_case.query,
        articles=articles,
        embedder=embedder,
        article_vectors=article_vectors,
        top_k=TOP_K,
    )
    answer, generation_latency_ms = generate_grounded_answer(query_case.query, retrieved)
    retrieved_context = "\n\n".join(chunk.content for chunk in retrieved)
    prompt = f"Context:\n{retrieved_context}\n\nQuestion: {query_case.query}"

    total_latency_ms = embedding_latency_ms + retrieval_latency_ms + generation_latency_ms
    input_tokens = token_count(prompt)
    output_tokens = token_count(answer)
    total_tokens = input_tokens + output_tokens

    return {
        "query_id": query_case.query_id,
        "query": query_case.query,
        "expected_title": query_case.expected_title,
        "retrieved_titles": " | ".join(chunk.title for chunk in retrieved),
        "answer": answer,
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens,
        "embedding_latency_ms": round(embedding_latency_ms, 3),
        "retrieval_latency_ms": round(retrieval_latency_ms, 3),
        "generation_latency_ms": round(generation_latency_ms, 3),
        "total_latency_ms": round(total_latency_ms, 3),
        "answer_relevance": answer_relevance(query_case.query, answer, embedder),
        "faithfulness": faithfulness(answer, retrieved),
        "context_precision": context_precision(query_case, retrieved),
    }


def plot_query_metrics(row: dict) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].bar(
        ["tokens", "latency ms"],
        [row["total_tokens"], row["total_latency_ms"]],
        color=["#2563eb", "#dc2626"],
    )
    axes[0].set_title(f"{row['query_id']} Tokens and Latency")
    axes[0].grid(axis="y", alpha=0.3)

    axes[1].bar(
        ["relevance", "faithfulness", "context precision"],
        [row["answer_relevance"], row["faithfulness"], row["context_precision"]],
        color=["#16a34a", "#9333ea", "#f59e0b"],
    )
    axes[1].set_ylim(0, 1.05)
    axes[1].set_title(f"{row['query_id']} Quality Metrics")
    axes[1].tick_params(axis="x", rotation=15)
    axes[1].grid(axis="y", alpha=0.3)

    fig.suptitle(row["query"], fontsize=11)
    fig.tight_layout()
    fig.savefig(PLOTS_DIR / f"{row['query_id'].lower()}_metrics.png", dpi=150)
    plt.close(fig)


def plot_summary(results: list[dict]) -> None:
    frame = pd.DataFrame(results)
    fig, axes = plt.subplots(2, 1, figsize=(12, 9))

    axes[0].plot(frame["query_id"], frame["total_tokens"], marker="o", label="Total tokens")
    axes[0].plot(frame["query_id"], frame["total_latency_ms"], marker="o", label="Total latency ms")
    axes[0].set_title("Token Count and Latency by Query")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    for metric in ["answer_relevance", "faithfulness", "context_precision"]:
        axes[1].plot(frame["query_id"], frame[metric], marker="o", label=metric)
    axes[1].set_ylim(0, 1.05)
    axes[1].set_title("RAG Quality Metrics by Query")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    fig.tight_layout()
    fig.savefig(PLOTS_DIR / "all_queries_summary.png", dpi=150)
    plt.close(fig)


def write_report(results: list[dict]) -> None:
    frame = pd.DataFrame(results)
    report = [
        "# Day 13 Task 2: RAG Metrics and Latency Evaluation",
        "",
        "This task evaluates each query using token count, latency, answer relevance, faithfulness, and context precision.",
        "",
        "## Metrics",
        "",
        "| Metric | Meaning |",
        "| --- | --- |",
        "| Token count | Total prompt/context plus generated answer tokens |",
        "| Latency | Embedding, retrieval, generation, and total latency in milliseconds |",
        "| Answer relevance | Similarity between the query and generated answer |",
        "| Faithfulness | Share of answer terms supported by retrieved context |",
        "| Context precision | Share of retrieved chunks relevant to the expected answer/context |",
        "",
        "## Final Summary",
        "",
        f"- Average total tokens: {frame['total_tokens'].mean():.2f}",
        f"- Average total latency ms: {frame['total_latency_ms'].mean():.2f}",
        f"- Average answer relevance: {frame['answer_relevance'].mean():.3f}",
        f"- Average faithfulness: {frame['faithfulness'].mean():.3f}",
        f"- Average context precision: {frame['context_precision'].mean():.3f}",
        "",
        "## Output Graphs",
        "",
        "- `plots/all_queries_summary.png`",
    ]
    report.extend(f"- `plots/{row['query_id'].lower()}_metrics.png`" for row in results)
    report.append("")
    (OUTPUT_DIR / "rag_metrics_report.md").write_text("\n".join(report), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Day 13 Task 2 RAG metric evaluation.")
    parser.add_argument("--top-k", type=int, default=TOP_K, help="Included for classroom compatibility; default is 3.")
    return parser.parse_args([]) # Modified to handle Jupyter/Colab execution


def main() -> None:
    parse_args()
    OUTPUT_DIR.mkdir(exist_ok=True)
    PLOTS_DIR.mkdir(exist_ok=True)

    embedder = LocalHashingEmbedder(dimensions=EMBEDDING_DIM)
    article_vectors = embedder.embed_documents([article.content for article in ARTICLES])

    results = [
        evaluate_query(query_case, ARTICLES, embedder, article_vectors)
        for query_case in QUERY_CASES
    ]

    for row in results:
        plot_query_metrics(row)
    plot_summary(results)

    frame = pd.DataFrame(results)
    frame.to_csv(OUTPUT_DIR / "rag_metrics_by_query.csv", index=False)
    (OUTPUT_DIR / "rag_metrics_by_query.json").write_text(
        json.dumps(results, indent=2),
        encoding="utf-8",
    )
    write_report(results)

    print("Day 13 Task 2 complete.")
    print(f"Output folder: {OUTPUT_DIR}")
    print("Metrics: tokens, latency, answer relevance, faithfulness, context precision")


if __name__ == "__main__":
    main()

report_path = OUTPUT_DIR / "rag_metrics_report.md"
if report_path.exists():
    with open(report_path, "r", encoding="utf-8") as f:
        print(f.read())
else:
    print(f"Report file not found at {report_path}")